package main

import (
	"bytes"
	"encoding/json"
	"path/filepath"
	"testing"

	"github.com/koorikla/compositionfactory/catalogue"
)

// TestRunFromFileEndToEnd drives run() exactly the way
// .github/workflows/catalogue.yml's own weekly job would if it were passed
// --from-file — the offline path every test in this package (and this
// repo's own dev sandbox, where a compiled Go binary cannot reach the
// network at all) uses instead of live mode. No test in this file, or
// anywhere else in this package, makes a real network request.
func TestRunFromFileEndToEnd(t *testing.T) {
	out := filepath.Join(t.TempDir(), "providers.json")
	var stdout, stderr bytes.Buffer

	err := run([]string{
		"--from-file", filepath.Join("testdata", "manifest.json"),
		"--out", out,
		"--org", "crossplane-contrib",
	}, &stdout, &stderr)
	if err != nil {
		t.Fatalf("run: %v (stderr: %s)", err, stderr.String())
	}

	raw := readFile(t, out)
	var entries []catalogue.Provider
	if err := json.Unmarshal(raw, &entries); err != nil {
		t.Fatalf("output is not valid JSON: %v", err)
	}
	if err := catalogue.Validate(entries); err != nil {
		t.Fatalf("run produced an invalid catalogue: %v", err)
	}

	byName := make(map[string]catalogue.Provider, len(entries))
	for _, e := range entries {
		byName[e.Name] = e
	}

	if len(entries) != 3 {
		t.Fatalf("got %d entries, want 3 (matching testdata/manifest.json): %+v", len(entries), entries)
	}
	if got := byName["function-go-templating"].Ref; got != "ghcr.io/crossplane-contrib/function-go-templating:v0.11.0" {
		t.Errorf("function-go-templating ref = %q, want the latest stable tag, pseudo-version excluded", got)
	}
	if got := byName["provider-aws"].Ref; got != "ghcr.io/crossplane-contrib/provider-aws:v0.48.0" {
		t.Errorf("provider-aws ref = %q, want v0.48.0", got)
	}
	if got := byName["provider-upjet-aws"].Ref; got != "" {
		t.Errorf("provider-upjet-aws ref = %q, want empty — no tags entry in the manifest at all, labelled not dropped", got)
	}
	if _, ok := byName["provider-upjet-aws"]; !ok {
		t.Error("provider-upjet-aws is missing from the catalogue entirely — an unresolved repo must still be labelled, not hidden")
	}

	if stdout.Len() == 0 {
		t.Error("run produced no stdout summary")
	}
}

// TestRunFromFileIncludesUpjetFamilyServices drives run() with a manifest
// that carries an upjet family (see family.go) alongside ordinary repos, the
// --from-file equivalent of the live regeneration that fixed this
// catalogue's "provider-aws-rds is missing" gap. It pins that a family
// service (provider-aws-rds) ends up in the output with a resolved ref built
// from the *service's own* package name, sitting alongside the repo-derived
// entries and the family repo's own (still Ref=="") entry, all three
// surviving catalogue.Validate together.
func TestRunFromFileIncludesUpjetFamilyServices(t *testing.T) {
	dir := t.TempDir()
	manifestPath := filepath.Join(dir, "manifest.json")
	writeFile(t, manifestPath, `{
		"repos": [
			{"name": "provider-upjet-aws", "description": "AWS support for Crossplane, generated by Upjet", "html_url": "https://github.com/crossplane-contrib/provider-upjet-aws", "license_spdx_id": "Apache-2.0"}
		],
		"tags": {},
		"families": [
			{
				"repo": "provider-upjet-aws",
				"description": "AWS support for Crossplane, generated by Upjet",
				"html_url": "https://github.com/crossplane-contrib/provider-upjet-aws",
				"license_spdx_id": "Apache-2.0",
				"services": ["rds", "s3", "sqs"],
				"tags": {
					"provider-family-aws": ["v2.6.0", "v2.7.0"],
					"provider-aws-rds": ["v2.6.0", "v2.7.0"]
				}
			}
		]
	}`)

	out := filepath.Join(dir, "providers.json")
	var stdout, stderr bytes.Buffer
	err := run([]string{
		"--from-file", manifestPath,
		"--out", out,
		"--org", "crossplane-contrib",
	}, &stdout, &stderr)
	if err != nil {
		t.Fatalf("run: %v (stderr: %s)", err, stderr.String())
	}

	var entries []catalogue.Provider
	if err := json.Unmarshal(readFile(t, out), &entries); err != nil {
		t.Fatalf("output is not valid JSON: %v", err)
	}
	if err := catalogue.Validate(entries); err != nil {
		t.Fatalf("run produced an invalid catalogue: %v", err)
	}

	byName := make(map[string]catalogue.Provider, len(entries))
	for _, e := range entries {
		byName[e.Name] = e
	}

	// The searchability bug this whole file exists to fix: provider-aws-rds
	// must be present, with a pullable ref, even though no
	// crossplane-contrib/provider-aws-rds GitHub repository exists.
	rds, ok := byName["provider-aws-rds"]
	if !ok {
		t.Fatal("provider-aws-rds is missing from the catalogue entirely")
	}
	if want := "ghcr.io/crossplane-contrib/provider-aws-rds:v2.7.0"; rds.Ref != want {
		t.Errorf("provider-aws-rds ref = %q, want %q", rds.Ref, want)
	}

	// s3 and sqs were not individually resolved in the manifest's family
	// tags — they must still appear, inheriting the family's own v2.7.0 tag.
	for _, name := range []string{"provider-aws-s3", "provider-aws-sqs"} {
		e, ok := byName[name]
		if !ok {
			t.Errorf("%s is missing from the catalogue entirely", name)
			continue
		}
		want := "ghcr.io/crossplane-contrib/" + name + ":v2.7.0"
		if e.Ref != want {
			t.Errorf("%s ref = %q, want the family-inherited tag %q", name, e.Ref, want)
		}
	}

	// The family repo itself still gets its own repo-derived entry, labelled
	// (not dropped) since crossplane-contrib/provider-upjet-aws has no
	// ghcr.io image of its own.
	if fam, ok := byName["provider-upjet-aws"]; !ok {
		t.Error("provider-upjet-aws (the family repo's own entry) is missing")
	} else if fam.Ref != "" {
		t.Errorf("provider-upjet-aws ref = %q, want empty", fam.Ref)
	}
}

func TestRunErrorsOnMissingManifest(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := run([]string{"--from-file", filepath.Join(t.TempDir(), "nope.json")}, &stdout, &stderr)
	if err == nil {
		t.Fatal("run with a missing manifest = nil error, want one")
	}
}

func TestRunRejectsUnknownFlag(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := run([]string{"--bogus-flag"}, &stdout, &stderr)
	if err == nil {
		t.Fatal("run with an unknown flag = nil error, want one")
	}
}
