package main

import (
	"path/filepath"
	"reflect"
	"testing"
)

func TestLoadManifestParsesReposAndTags(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "manifest.json")
	writeFile(t, path, `{
		"repos": [
			{"name": "function-go-templating", "description": "go templates", "html_url": "https://github.com/crossplane-contrib/function-go-templating", "license_spdx_id": "Apache-2.0"},
			{"name": "provider-upjet-aws", "description": "aws generator", "html_url": "https://github.com/crossplane-contrib/provider-upjet-aws", "license_spdx_id": ""}
		],
		"tags": {
			"function-go-templating": ["v0.9.2", "v0.10.0", "v0.11.0"]
		}
	}`)

	m, err := loadManifest(path)
	if err != nil {
		t.Fatalf("loadManifest: %v", err)
	}

	repos := m.repos("crossplane-contrib")
	want := []repo{
		{Name: "function-go-templating", Owner: "crossplane-contrib", Description: "go templates", SourceURL: "https://github.com/crossplane-contrib/function-go-templating", LicenseSPDX: "Apache-2.0"},
		{Name: "provider-upjet-aws", Owner: "crossplane-contrib", Description: "aws generator", SourceURL: "https://github.com/crossplane-contrib/provider-upjet-aws", LicenseSPDX: ""},
	}
	if !reflect.DeepEqual(repos, want) {
		t.Errorf("repos = %+v, want %+v", repos, want)
	}

	wantTags := map[string][]string{"function-go-templating": {"v0.9.2", "v0.10.0", "v0.11.0"}}
	if !reflect.DeepEqual(m.Tags, wantTags) {
		t.Errorf("tags = %+v, want %+v", m.Tags, wantTags)
	}
}

func TestLoadManifestParsesFamilies(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "manifest.json")
	writeFile(t, path, `{
		"repos": [],
		"tags": {},
		"families": [
			{
				"repo": "provider-upjet-aws",
				"description": "AWS support for Crossplane, generated by Upjet",
				"html_url": "https://github.com/crossplane-contrib/provider-upjet-aws",
				"license_spdx_id": "Apache-2.0",
				"services": ["rds", "s3"],
				"tags": {
					"provider-family-aws": ["v2.6.0", "v2.7.0"],
					"provider-aws-rds": ["v2.6.0", "v2.7.0"]
				}
			}
		]
	}`)

	m, err := loadManifest(path)
	if err != nil {
		t.Fatalf("loadManifest: %v", err)
	}

	families := m.families("crossplane-contrib")
	want := []family{
		{
			Repo: repo{
				Name:        "provider-upjet-aws",
				Owner:       "crossplane-contrib",
				Description: "AWS support for Crossplane, generated by Upjet",
				SourceURL:   "https://github.com/crossplane-contrib/provider-upjet-aws",
				LicenseSPDX: "Apache-2.0",
			},
			Cloud:    "aws",
			Services: []string{"rds", "s3"},
		},
	}
	if !reflect.DeepEqual(families, want) {
		t.Errorf("families = %+v, want %+v", families, want)
	}

	gotTags := m.familyTags("provider-upjet-aws")
	wantTags := map[string][]string{
		"provider-family-aws": {"v2.6.0", "v2.7.0"},
		"provider-aws-rds":    {"v2.6.0", "v2.7.0"},
	}
	if !reflect.DeepEqual(gotTags, wantTags) {
		t.Errorf("familyTags = %v, want %v", gotTags, wantTags)
	}

	if got := m.familyTags("does-not-exist"); got != nil {
		t.Errorf("familyTags for an unknown repo = %v, want nil", got)
	}
}

func TestManifestFamiliesIsEmptyWhenAbsent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "manifest.json")
	writeFile(t, path, `{"repos": [], "tags": {}}`)

	m, err := loadManifest(path)
	if err != nil {
		t.Fatalf("loadManifest: %v", err)
	}
	if got := m.families("crossplane-contrib"); len(got) != 0 {
		t.Errorf("families = %+v, want none — a manifest predating family.go must still load", got)
	}
}

func TestLoadManifestErrorsOnMissingFile(t *testing.T) {
	if _, err := loadManifest(filepath.Join(t.TempDir(), "does-not-exist.json")); err == nil {
		t.Fatal("loadManifest on a missing file = nil error, want one")
	}
}

func TestLoadManifestErrorsOnInvalidJSON(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "manifest.json")
	writeFile(t, path, `not json`)
	if _, err := loadManifest(path); err == nil {
		t.Fatal("loadManifest on invalid JSON = nil error, want one")
	}
}
