// Slice 27 — the output drawer grows blocks beyond the DSL: a tab per
// generated providerconfig (annotated with the kind-picker state) and an
// RBAC tab from GET /api/rbac.
const { test, expect } = require('@playwright/test')
const { resetDoc, ENGINE } = require('./helpers')

test.beforeEach(async ({ request, page }) => {
  await resetDoc(request)
  await page.goto('/')
  await page.evaluate(() => localStorage.removeItem('cf-hidden-kinds'))
})

test('a providerconfigs tab appears per family and renders the real scaffold', async ({ page }) => {
  await page.goto('/')
  const tab = page.locator('#tabs button[data-t="pc:aws"]')
  await expect(tab).toBeVisible()
  await expect(tab).toHaveText('providerconfigs/aws.yaml')
  await tab.click()
  await expect(page.locator('#code')).toContainText('kind: ClusterProviderConfig')
  await expect(page.locator('#code')).toContainText('Generated by compositionfactory')
})

test('the providerconfigs tab is annotated with the kind-picker state', async ({ page }) => {
  await page.goto('/')
  // hide all but Queue for the sqs provider, then look at the annotation
  await page.click('#rtabs button[data-r="src"]')
  await page.click('#lrail .src-row', { position: { x: 40, y: 10 } })
  await page.uncheck('#lrail .src-detail input[data-pick-kind="QueuePolicy"][data-av*=".m."]')
  await page.click('#tabs button[data-t="pc:aws"]')
  const note = page.locator('#pc-note')
  await expect(note).toContainText(/provider-aws-sqs/)
  await expect(note).toContainText(/1 kind hidden|hidden: 1/i)
})

test('an RBAC tab renders the rule list from the live endpoint', async ({ page }) => {
  await page.goto('/')
  await page.click('#tabs button[data-t="rbac"]')
  const code = page.locator('#code')
  await expect(code).toContainText('apiGroups')
  await expect(code).toContainText('sqs.aws.m.upbound.io')
  await expect(code).toContainText('queues')
  await expect(code).toContainText(/get.*list.*watch/s)
})
