package manifest

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRoundTripGoldenCompositions(t *testing.T) {
	paths := []string{
		"../emit/testdata/native-composition.golden.yaml",
		"../emit/testdata/pipeline_composition.golden.yaml",
		"../../testdata/xqueue-pipeline.composition.golden.yaml",
	}

	for _, relPath := range paths {
		t.Run(filepath.Base(relPath), func(t *testing.T) {
			raw, err := os.ReadFile(relPath)
			if err != nil {
				t.Fatalf("failed to read test fixture: %v", err)
			}

			m, err := ParseComposition(raw)
			if err != nil {
				t.Fatalf("ParseComposition failed: %v", err)
			}

			// Apply with zero edits must be 100% byte-identical
			patched, err := Apply(m)
			if err != nil {
				t.Fatalf("Apply failed: %v", err)
			}

			if !bytes.Equal(patched, raw) {
				t.Fatalf("Round-trip identity failure: output differs from input\nGot:\n%s\nWant:\n%s", string(patched), string(raw))
			}
		})
	}
}

func TestSingleFieldLiteralSplice(t *testing.T) {
	raw, err := os.ReadFile("../emit/testdata/native-composition.golden.yaml")
	if err != nil {
		t.Fatalf("failed to read fixture: %v", err)
	}

	m, err := ParseComposition(raw)
	if err != nil {
		t.Fatalf("ParseComposition failed: %v", err)
	}

	if len(m.Resources) == 0 {
		t.Fatalf("expected parsed resources, got 0")
	}

	queueRes := m.Resources[0]
	if queueRes.Name != "main-queue" {
		t.Fatalf("expected resource main-queue, got %s", queueRes.Name)
	}

	edit, err := SetFieldLiteral(queueRes, "region", "us-east-1")
	if err != nil {
		t.Fatalf("SetFieldLiteral failed: %v", err)
	}

	patched, err := Apply(m, edit)
	if err != nil {
		t.Fatalf("Apply edit failed: %v", err)
	}

	if !strings.Contains(string(patched), "region: 'us-east-1'") {
		t.Errorf("expected patched output to contain region: 'us-east-1'\nGot:\n%s", string(patched))
	}
	if strings.Contains(string(patched), "region: 'eu-north-1'") {
		t.Errorf("expected old region to be replaced")
	}

	// Verify that header comments were preserved
	if !strings.Contains(string(patched), "# Generated by compositionfactory. Do not edit.") {
		t.Errorf("header comments were destroyed")
	}
}

func TestSingleFieldWireSplice(t *testing.T) {
	raw, err := os.ReadFile("../emit/testdata/native-composition.golden.yaml")
	if err != nil {
		t.Fatalf("failed to read fixture: %v", err)
	}

	m, err := ParseComposition(raw)
	if err != nil {
		t.Fatalf("ParseComposition failed: %v", err)
	}

	// Resource 1 is "web" Deployment
	if len(m.Resources) < 2 {
		t.Fatalf("expected at least 2 resources, got %d", len(m.Resources))
	}

	deployRes := m.Resources[1]
	edit, err := SetFieldWire(deployRes, "image", "customImage", false)
	if err != nil {
		t.Fatalf("SetFieldWire failed: %v", err)
	}

	patched, err := Apply(m, edit)
	if err != nil {
		t.Fatalf("Apply edit failed: %v", err)
	}

	if !strings.Contains(string(patched), "image: {{ $spec.customImage }}") {
		t.Errorf("expected patched image wire\nGot:\n%s", string(patched))
	}
}

func TestPreservationFixtures(t *testing.T) {
	const customDoc = `# Custom top-level comment
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcustom.example.org
  labels:
    team: backend-infra
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XCustom
  mode: Pipeline
  pipeline:
  - step: extra-step
    functionRef:
      name: function-custom-enricher
  - step: render-resources
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      options: ["missingkey=error"]
      inline:
        template: |
          {{- $spec := .observed.composite.resource.spec -}}
          {{- $xr := .observed.composite.resource.metadata.name -}}
          {{- $xrMeta := .observed.composite.resource.metadata -}}
          # Custom template comment inside body
          {{- range $i, $item := $spec.customList }}
          ---
          apiVersion: v1
          kind: ConfigMap
          metadata:
            annotations:
              {{ setResourceNameAnnotation "custom-item" }}
          data:
            item: 'val'
          {{- end }}
          ---
          apiVersion: sqs.aws.m.upbound.io/v1beta1
          kind: Queue
          metadata:
            annotations:
              {{ setResourceNameAnnotation "my-queue" }}
          spec:
            forProvider:
              region: 'eu-west-1'
`

	current := []byte(customDoc)

	// Run 3 successive parse-edit-save cycles
	for cycle := 1; cycle <= 3; cycle++ {
		m, err := ParseComposition(current)
		if err != nil {
			t.Fatalf("cycle %d: ParseComposition failed: %v", cycle, err)
		}

		// Find my-queue and edit region
		var queueRes *ParsedResource
		for _, r := range m.Resources {
			if r.Name == "my-queue" {
				queueRes = r
				break
			}
		}
		if queueRes == nil {
			t.Fatalf("cycle %d: my-queue resource not found", cycle)
		}

		edit, err := SetFieldLiteral(queueRes, "region", "us-east-2")
		if err != nil {
			t.Fatalf("cycle %d: SetFieldLiteral failed: %v", cycle, err)
		}

		saved, err := Apply(m, edit)
		if err != nil {
			t.Fatalf("cycle %d: Apply failed: %v", cycle, err)
		}

		current = saved
	}

	result := string(current)

	// Assert preservation of all custom elements
	if !strings.Contains(result, "# Custom top-level comment") {
		t.Errorf("custom top comment lost")
	}
	if !strings.Contains(result, "team: backend-infra") {
		t.Errorf("custom label lost")
	}
	if !strings.Contains(result, "name: function-custom-enricher") {
		t.Errorf("custom pipeline step lost")
	}
	if !strings.Contains(result, "# Custom template comment inside body") {
		t.Errorf("custom template comment lost")
	}
	if !strings.Contains(result, "{{- range $i, $item := $spec.customList }}") {
		t.Errorf("custom range loop block lost")
	}
	if !strings.Contains(result, "region: 'us-east-2'") {
		t.Errorf("edited field not updated correctly")
	}
}

func TestScrubKubectlExport(t *testing.T) {
	const kubectlExport = `apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xqueues.platform.sparky.ee
  generation: 4
  resourceVersion: "987654321"
  uid: "123e4567-e89b-12d3-a456-426614174000"
  creationTimestamp: "2026-09-02T12:00:00Z"
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apiextensions.crossplane.io/v1"}'
    user.annotation/retain: "true"
spec:
  compositeTypeRef:
    apiVersion: platform.sparky.ee/v1alpha1
    kind: XQueue
status:
  conditions:
  - lastTransitionTime: "2026-09-02T12:00:05Z"
    status: "True"
    type: Ready
`

	scrubbed, removed, err := ScrubKubectlExport([]byte(kubectlExport))
	if err != nil {
		t.Fatalf("ScrubKubectlExport failed: %v", err)
	}

	if removed < 5 {
		t.Errorf("expected at least 5 removed server-side fields, got %d", removed)
	}

	outStr := string(scrubbed)
	if strings.Contains(outStr, "resourceVersion") {
		t.Errorf("resourceVersion was not scrubbed")
	}
	if strings.Contains(outStr, "uid:") {
		t.Errorf("uid was not scrubbed")
	}
	if strings.Contains(outStr, "status:") {
		t.Errorf("status was not scrubbed")
	}
	if strings.Contains(outStr, "kubectl.kubernetes.io/last-applied-configuration") {
		t.Errorf("last-applied-configuration was not scrubbed")
	}
	if !strings.Contains(outStr, "user.annotation/retain: \"true\"") {
		t.Errorf("user annotation was incorrectly stripped")
	}
}
