package emit

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/koorikla/compositionfactory/internal/blueprint"
)

func TestCF494_EnvironmentConfigHeader_DoesNotSayDoNotEdit(t *testing.T) {
	bpYAML := `
apiVersion: factory.crossplane.io/v1alpha1
kind: Blueprint
metadata:
  name: cloud-database
spec:
  sources:
    - provider: xpkg.upbound.io/upbound/provider-aws-sqs:v2
  xrd:
    group: database.sparky.ee
    kind: XDatabase
    plural: xdatabases
    version: v1alpha1
    scope: Namespaced
    parameters:
      providerName: {type: string, required: true}
  environment:
    password:
      type: string
      description: Master password for PostgreSQL.
  resources:
    - name: main-queue
      kind: Queue
      provider: xpkg.upbound.io/upbound/provider-aws-sqs:v2
      fields:
        region: {value: "us-east-1"}
`
	bp, err := blueprint.Parse([]byte(bpYAML))
	if err != nil {
		t.Fatalf("blueprint.Parse: %v", err)
	}

	cfg := blueprint.EnvironmentConfig{
		Name: "default",
	}

	out, err := EnvironmentConfig(bp, cfg)
	if err != nil {
		t.Fatalf("EnvironmentConfig: %v", err)
	}

	outStr := string(out)

	if strings.Contains(strings.ToLower(outStr), "do not edit") {
		t.Errorf("EnvironmentConfig header must NOT tell operator 'Do not edit', got:\n%s", outStr)
	}

	if !strings.Contains(outStr, "preserved across regeneration") {
		t.Errorf("EnvironmentConfig header must inform operator that values are preserved across regeneration, got:\n%s", outStr)
	}

	if !strings.Contains(outStr, "Generated by compositionfactory.") {
		t.Errorf("EnvironmentConfig header must indicate generated provenance, got:\n%s", outStr)
	}

	// Verify end-to-end via Generate that environmentconfigs/*.yaml carries the true header
	// while other artifacts (XRD, Composition, functions, RBAC) still tell the operator "Do not edit."
	crds := testCRDs(t)
	outDir := t.TempDir()
	outputs, err := Generate(bp, crds, outDir)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	var envOut *Output
	var xrdOut *Output
	for i := range outputs {
		p := filepath.ToSlash(outputs[i].Path)
		if strings.HasSuffix(p, "environmentconfigs/default.yaml") {
			envOut = &outputs[i]
		}
		if strings.HasSuffix(p, "xrds/xdatabases.database.sparky.ee.yaml") {
			xrdOut = &outputs[i]
		}
	}

	if envOut == nil {
		t.Fatalf("missing environmentconfigs/default.yaml in generate outputs")
	}
	envBody := string(envOut.Body)
	if strings.Contains(strings.ToLower(envBody), "do not edit") {
		t.Errorf("emitted environmentconfigs/default.yaml must NOT contain 'Do not edit', got:\n%s", envBody)
	}
	if !strings.Contains(envBody, "preserved across regeneration") {
		t.Errorf("emitted environmentconfigs/default.yaml must mention 'preserved across regeneration', got:\n%s", envBody)
	}

	if xrdOut == nil {
		t.Fatalf("missing xrds output in generate outputs")
	}
	xrdBody := string(xrdOut.Body)
	if !strings.Contains(xrdBody, "Do not edit.") {
		t.Errorf("XRD output must still carry 'Do not edit.', got:\n%s", xrdBody)
	}
}
