package emit

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

var (
	kclBoolTrueRE  = regexp.MustCompile(`\btrue\b`)
	kclBoolFalseRE = regexp.MustCompile(`\bfalse\b`)
)

// kclTemplateBody generates idiomatic KCL code for function-kcl (krm.kcl.dev/v1alpha1).
func kclTemplateBody(b *blueprint.Blueprint, crds []schema.CRD) (string, error) {
	if len(b.Spec.Environment) > 0 {
		return "", fmt.Errorf("spec.environment: engine %q does not support spec.environment", b.Engine())
	}
	if err := refuseGoTemplateOnlyFeatures(b); err != nil {
		return "", err
	}

	x := b.Spec.XRD
	wantNamespaced := x.Scope == "Namespaced"

	var sb strings.Builder
	sb.WriteString("# Generated by compositionfactory. Do not edit.\n")
	sb.WriteString("import base64\n\n")
	sb.WriteString("oxr = option(\"params\")?.oxr or {}\n")
	sb.WriteString("ocds = option(\"params\")?.ocds or {}\n")
	sb.WriteString("dxr = option(\"params\")?.dxr or {}\n")
	sb.WriteString("dcds = option(\"params\")?.dcds or {}\n")
	sb.WriteString("_spec = oxr?.spec or {}\n")
	sb.WriteString("_xr = oxr?.metadata?.name or \"\"\n")
	sb.WriteString("_xrMeta = oxr?.metadata or {}\n\n")

	sb.WriteString("_items = [\n")

	for _, r := range b.Spec.Resources {
		pres, err := planSingleResource(r, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}
		crd := pres.CRD
		apiVersion := pres.APIVersion
		annPlan := pres.AnnPlan
		bodyPlan := pres.BodyPlan
		envPlan := pres.EnvPlan

		indent := "    "
		if r.When != "" {
			condKCL := translateWhenToKCL(r.When)
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, condKCL))
			indent = "        "
		}

		if r.ForEach != "" {
			sb.WriteString(fmt.Sprintf("%s*[\n", indent))
			indent = indent + "    "
		}

		sb.WriteString(fmt.Sprintf("%s{\n", indent))
		inner := indent + "    "
		sb.WriteString(fmt.Sprintf("%sapiVersion = %q\n", inner, apiVersion))
		sb.WriteString(fmt.Sprintf("%skind = %q\n", inner, crd.Kind))

		// Metadata
		sb.WriteString(fmt.Sprintf("%smetadata = {\n", inner))
		metaInner := inner + "    "
		if crd.Native {
			var metaName *forProviderField
			for i := range pres.MetaPlan {
				if pres.MetaPlan[i].path == "metadata.name" || pres.MetaPlan[i].path == "name" {
					metaName = &pres.MetaPlan[i]
					break
				}
			}
			if metaName != nil {
				rhs := kclStructuredRHS(metaName.structured, metaName.rhs)
				if r.ForEach != "" {
					rhs = kclLoopedRHS(rhs)
				}
				if metaName.structured.kind == rhsStatus {
					raw := kclRawStatusAccess(metaName.structured)
					sb.WriteString(fmt.Sprintf("%sif %s != None:\n", metaInner, raw))
					sb.WriteString(fmt.Sprintf("%s    name = %s\n", metaInner, rhs))
				} else if isNested, guardExpr := kclNestedParamGuard(metaName.structured, metaName.rhs); isNested {
					sb.WriteString(fmt.Sprintf("%sif %s != None:\n", metaInner, guardExpr))
					sb.WriteString(fmt.Sprintf("%s    name = %s\n", metaInner, rhs))
				} else {
					sb.WriteString(fmt.Sprintf("%sname = %s\n", metaInner, rhs))
				}
			} else {
				if r.ForEach != "" {
					sb.WriteString(fmt.Sprintf("%sname = \"${_xr}-%s-${_i}\"\n", metaInner, r.Name))
				} else {
					sb.WriteString(fmt.Sprintf("%sname = \"${_xr}-%s\"\n", metaInner, r.Name))
				}
			}
		}
		sb.WriteString(fmt.Sprintf("%sannotations = {\n", metaInner))
		annInner := metaInner + "    "
		if r.ForEach != "" {
			sb.WriteString(fmt.Sprintf("%s\"krm.kcl.dev/composition-resource-name\" = \"%s-${_i}\"\n", annInner, r.Name))
		} else {
			sb.WriteString(fmt.Sprintf("%s\"krm.kcl.dev/composition-resource-name\" = %q\n", annInner, r.Name))
		}
		for _, ann := range annPlan {
			rhs := kclStructuredRHS(ann.structured, ann.rhs)
			if ann.structured.kind == rhsStatus {
				raw := kclRawStatusAccess(ann.structured)
				sb.WriteString(fmt.Sprintf("%sif %s != None:\n", annInner, raw))
				sb.WriteString(fmt.Sprintf("%s    %q = %s\n", annInner, ann.path, rhs))
			} else if isNested, guardExpr := kclNestedParamGuard(ann.structured, ann.rhs); isNested {
				sb.WriteString(fmt.Sprintf("%sif %s != None:\n", annInner, guardExpr))
				sb.WriteString(fmt.Sprintf("%s    %q = %s\n", annInner, ann.path, rhs))
			} else {
				sb.WriteString(fmt.Sprintf("%s%q = %s\n", annInner, ann.path, rhs))
			}
		}
		sb.WriteString(fmt.Sprintf("%s}\n", metaInner))
		if crd.Native {
			otherMeta := otherNativeMetadata(pres.MetaPlan)
			if len(otherMeta) > 0 {
				root, err := buildNativeTree(r.Name, otherMeta)
				if err != nil {
					return "", err
				}
				writeKCLNodes(&sb, metaInner, root.children, "")
			}
		}
		sb.WriteString(fmt.Sprintf("%s}\n", inner))

		// Spec
		if crd.Native {
			root, err := buildNativeTree(r.Name, bodyPlan)
			if err != nil {
				return "", err
			}
			writeKCLNodes(&sb, inner, root.children, "")
		} else {
			sb.WriteString(fmt.Sprintf("%sspec = {\n", inner))
			specInner := inner + "    "

			// forProvider
			sb.WriteString(fmt.Sprintf("%sforProvider = {\n", specInner))
			root, err := buildNativeTree(r.Name, bodyPlan)
			if err != nil {
				return "", err
			}
			writeKCLNodes(&sb, specInner+"    ", root.children, "")
			sb.WriteString(fmt.Sprintf("%s}\n", specInner))

			hasPCRInPlan := false
			for _, ef := range envPlan {
				if len(ef.path) > 0 && ef.path[0] == "providerConfigRef" {
					hasPCRInPlan = true
					break
				}
			}
			if !hasPCRInPlan && wantNamespaced {
				providerNameRef := "_spec?.providerName or \"default\""
				if p, ok := b.Spec.XRD.Parameters["providerName"]; ok && p.Default != "" {
					providerNameRef = fmt.Sprintf("_spec?.providerName or %q", p.Default)
				}
				sb.WriteString(fmt.Sprintf("%sproviderConfigRef = {\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    kind = \"ClusterProviderConfig\"\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    name = %s\n", specInner, providerNameRef))
				sb.WriteString(fmt.Sprintf("%s}\n", specInner))
			}

			// envelope fields (nested objects)
			envTree := buildEnvTree(envPlan)
			writeKCLEnvelopeNodes(&sb, specInner, envTree, "")

			sb.WriteString(fmt.Sprintf("%s}\n", inner))
		}

		if r.ForEach != "" {
			loopExpr := translateForEachToKCL(r.ForEach)
			indent = indent[4:]
			sb.WriteString(fmt.Sprintf("%s} for _i in %s\n", indent+"    ", loopExpr))
			sb.WriteString(fmt.Sprintf("%s],\n", indent))
		} else {
			sb.WriteString(fmt.Sprintf("%s},\n", indent))
		}
	}

	sb.WriteString("]\n\n")
	sb.WriteString("items = _items\n")

	return sb.String(), nil
}

func writeKCLNodes(sb *strings.Builder, indent string, nodes []*nativeNode, inheritedGuard string) {
	for i := 0; i < len(nodes); {
		c := nodes[i]
		if !c.indexed {
			writeKCLNode(sb, indent, c, inheritedGuard)
			i++
			continue
		}
		j := i
		for j < len(nodes) && nodes[j].indexed && nodes[j].seg == c.seg {
			j++
		}
		run := nodes[i:j]
		i = j

		sb.WriteString(fmt.Sprintf("%s%s = [\n", indent, quoteKCLKey(c.seg)))
		for _, elem := range run {
			writeKCLElement(sb, indent+"    ", elem)
		}
		sb.WriteString(fmt.Sprintf("%s]\n", indent))
	}
}

func kclNestedParamGuard(s structuredRHS, fallbackRHS string) (bool, string) {
	if s.kind == rhsParam {
		if len(s.paramSegs) > 1 {
			return true, "_spec?." + strings.Join(s.paramSegs, "?.")
		}
		if len(s.paramSegs) == 0 && strings.Contains(s.param, ".") {
			return true, translateParamAccessToKCL(s.param)
		}
	} else if s.kind == rhsUnset {
		rhs := strings.TrimSpace(fallbackRHS)
		if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
			inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
			inner = strings.TrimSuffix(inner, "| quote")
			inner = strings.TrimSpace(inner)
			if strings.HasPrefix(inner, "$spec.") {
				param := strings.TrimPrefix(inner, "$spec.")
				if strings.Contains(param, ".") {
					return true, translateParamAccessToKCL(param)
				}
			}
		}
	}
	return false, ""
}

// nativeNodeAllOptional returns true if every leaf in the subtree rooted at n is optional.
func nativeNodeAllOptional(n *nativeNode) bool {
	if len(n.children) == 0 {
		return n.leaf != nil && (n.leaf.structured.optional || n.leaf.guard != "")
	}
	for _, child := range n.children {
		if !nativeNodeAllOptional(child) {
			return false
		}
	}
	return true
}

func kclNodeFieldGuard(f *forProviderField) string {
	if f == nil || (!f.structured.optional && f.guard == "") {
		return ""
	}
	if f.structured.kind == rhsParam {
		if len(f.structured.paramSegs) > 0 {
			return "_spec?." + strings.Join(f.structured.paramSegs, "?.") + " != None"
		}
		if f.structured.param != "" {
			return translateParamAccessToKCL(f.structured.param) + " != None"
		}
	} else if f.structured.kind == rhsStatus {
		return kclRawStatusAccess(f.structured) + " != None"
	} else if f.structured.kind == rhsEnv {
		if len(f.structured.paramSegs) > 0 {
			return "_env?." + strings.Join(f.structured.paramSegs, "?.") + " != None"
		}
		if f.structured.param != "" {
			return "_env?." + f.structured.param + " != None"
		}
	}
	if isNested, guardExpr := kclNestedParamGuard(f.structured, f.rhs); isNested {
		return guardExpr + " != None"
	}
	rhs := strings.TrimSpace(f.rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		inner = strings.TrimSuffix(inner, "| quote")
		inner = strings.TrimSpace(inner)
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			return translateParamAccessToKCL(param) + " != None"
		}
	}
	return ""
}

func collectKCLNativeSubtreeGuards(n *nativeNode, guards *[]string, seen map[string]bool) {
	if n.leaf != nil {
		if g := kclNodeFieldGuard(n.leaf); g != "" {
			if !seen[g] {
				seen[g] = true
				*guards = append(*guards, g)
			}
		}
	}
	for _, child := range n.children {
		collectKCLNativeSubtreeGuards(child, guards, seen)
	}
}

func writeKCLNode(sb *strings.Builder, indent string, n *nativeNode, inheritedGuard string) {
	if n.leaf != nil {
		rhs := kclStructuredRHS(n.leaf.structured, n.leaf.rhs)
		g := kclNodeFieldGuard(n.leaf)
		if g != "" && g != inheritedGuard {
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, g))
			sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.seg), rhs))
		} else if n.leaf.structured.kind == rhsStatus && inheritedGuard == "" {
			raw := kclRawStatusAccess(n.leaf.structured)
			sb.WriteString(fmt.Sprintf("%sif %s != None:\n", indent, raw))
			sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.seg), rhs))
		} else if isNested, guardExpr := kclNestedParamGuard(n.leaf.structured, n.leaf.rhs); isNested && inheritedGuard == "" {
			sb.WriteString(fmt.Sprintf("%sif %s != None:\n", indent, guardExpr))
			sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.seg), rhs))
		} else {
			sb.WriteString(fmt.Sprintf("%s%s = %s\n", indent, quoteKCLKey(n.seg), rhs))
		}
		return
	}

	allOptional := nativeNodeAllOptional(n)
	guard := ""
	if allOptional {
		var guards []string
		seen := make(map[string]bool)
		collectKCLNativeSubtreeGuards(n, &guards, seen)
		guard = strings.Join(guards, " or ")
	}

	wrap := guard != "" && guard != inheritedGuard
	curIndent := indent
	childInheritedGuard := inheritedGuard
	if wrap {
		sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, guard))
		curIndent = indent + "    "
		childInheritedGuard = guard
	}

	sb.WriteString(fmt.Sprintf("%s%s = {\n", curIndent, quoteKCLKey(n.seg)))
	writeKCLNodes(sb, curIndent+"    ", n.children, childInheritedGuard)
	sb.WriteString(fmt.Sprintf("%s}\n", curIndent))
}

func writeKCLElement(sb *strings.Builder, indent string, elem *nativeNode) {
	if elem.leaf != nil {
		rhs := kclStructuredRHS(elem.leaf.structured, elem.leaf.rhs)
		sb.WriteString(fmt.Sprintf("%s%s\n", indent, rhs))
		return
	}
	sb.WriteString(fmt.Sprintf("%s{\n", indent))
	writeKCLNodes(sb, indent+"    ", elem.children, "")
	sb.WriteString(fmt.Sprintf("%s}\n", indent))
}

func quoteKCLKey(k string) string {
	if strings.ContainsAny(k, "-./[]:") {
		return fmt.Sprintf("%q", k)
	}
	return k
}

func kclRawStatusAccess(s structuredRHS) string {
	return fmt.Sprintf("ocds?[%q]?.Resource?.status?.%s", s.resource, strings.ReplaceAll(s.statusPath, ".", "?."))
}

// kclLoopedRHS appends the loop index _i to a metadata.name RHS expression in KCL (CF-301).
func kclLoopedRHS(rhs string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, `"`) && strings.HasSuffix(rhs, `"`) && len(rhs) >= 2 {
		return rhs[:len(rhs)-1] + `-${_i}"`
	}
	if strings.HasPrefix(rhs, `'`) && strings.HasSuffix(rhs, `'`) && len(rhs) >= 2 {
		return rhs[:len(rhs)-1] + `-${_i}'`
	}
	return fmt.Sprintf(`"${%s}-${_i}"`, rhs)
}

func kclStructuredRHS(s structuredRHS, fallbackRHS string) string {
	switch s.kind {
	case rhsLiteral:
		return kclFormatLiteral(s.value, s.targetType)
	case rhsRaw:
		return s.value
	case rhsTemplate:
		return fmt.Sprintf("\"${_xr}-%s\"", s.value)
	case rhsParam:
		var expr string
		if len(s.paramSegs) > 0 {
			expr = "_spec?." + strings.Join(s.paramSegs, "?.")
		} else {
			expr = translateParamAccessToKCL(s.param)
		}
		if s.isByte {
			if s.sourceType != "" && s.sourceType != "string" {
				return fmt.Sprintf("base64.encode(str(%s))", expr)
			}
			return fmt.Sprintf("base64.encode(%s)", expr)
		}
		if s.targetType == "string" && s.sourceType != "" && s.sourceType != "string" {
			return fmt.Sprintf("str(%s)", expr)
		}
		return expr
	case rhsStatus:
		raw := kclRawStatusAccess(s)
		if s.isByte {
			if s.sourceType != "" && s.sourceType != "string" {
				return fmt.Sprintf("base64.encode(str(%s))", raw)
			}
			return fmt.Sprintf("base64.encode(%s)", raw)
		}
		if s.targetType == "string" {
			return fmt.Sprintf("str(%s)", raw)
		}
		return raw
	case rhsMetadata:
		expr := fmt.Sprintf("\"${_xr}-%s\"", s.resource)
		if s.isByte {
			return fmt.Sprintf("base64.encode(%s)", expr)
		}
		return expr
	case rhsEnv:
		expr := fmt.Sprintf("_env?.%s", s.param)
		if s.hasEnvDef {
			defVal := kclFormatLiteral(s.envDefault, s.sourceType)
			expr = fmt.Sprintf("_env?.%s or %s", s.param, defVal)
		}
		if s.isByte {
			if s.sourceType != "" && s.sourceType != "string" {
				return fmt.Sprintf("base64.encode(str(%s))", expr)
			}
			return fmt.Sprintf("base64.encode(%s)", expr)
		}
		if s.targetType == "string" && s.sourceType != "" && s.sourceType != "string" {
			return fmt.Sprintf("str(%s)", expr)
		}
		return expr
	default:
		return kclRHS(fallbackRHS, s.targetType)
	}
}

func kclRHS(rhs string, targetType string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		inner = strings.TrimSuffix(inner, "| quote")
		inner = strings.TrimSpace(inner)
		isByte := false
		if strings.HasSuffix(inner, "| b64enc") {
			isByte = true
			inner = strings.TrimSpace(strings.TrimSuffix(inner, "| b64enc"))
		}
		var res string
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			res = translateParamAccessToKCL(param)
		} else if strings.HasPrefix(inner, "$observed.") {
			res = translateObservedAccessToKCL(inner)
		}
		if res != "" {
			if isByte {
				return fmt.Sprintf("base64.encode(%s)", res)
			}
			return res
		}
	}
	return kclFormatLiteral(rhs, targetType)
}

func translateParamAccessToKCL(param string) string {
	parts := strings.Split(param, ".")
	return "_spec?." + strings.Join(parts, "?.")
}

func translateObservedAccessToKCL(expr string) string {
	return expr
}

func translateWhenToKCL(when string) string {
	when = strings.TrimSpace(when)
	source, name, op, literal, err := blueprint.ParseWhen(when)
	if err == nil {
		target := "_spec?."
		if source == "env" {
			target = "_env?."
		}
		switch op {
		case "":
			return fmt.Sprintf("%s%s", target, name)
		case "==":
			return fmt.Sprintf("%s%s == %q", target, name, literal)
		case "!=":
			return fmt.Sprintf("%s%s != %q", target, name, literal)
		}
	}
	when = strings.ReplaceAll(when, "params.", "_spec?.")
	when = kclBoolTrueRE.ReplaceAllString(when, "True")
	when = kclBoolFalseRE.ReplaceAllString(when, "False")
	return when
}

func translateForEachToKCL(forEach string) string {
	if strings.HasPrefix(forEach, "params.") {
		param := strings.TrimPrefix(forEach, "params.")
		return fmt.Sprintf("range(0, int(_spec?.%s or 0))", param)
	}
	if strings.HasPrefix(forEach, "resources.") {
		res, path, _ := blueprint.StatusRef(forEach)
		return fmt.Sprintf("range(0, int(ocds?[%q]?.Resource?.status?.%s or 0))", res, strings.ReplaceAll(path, ".", "?."))
	}
	return "range(0, 0)"
}

func kclFormatLiteral(val string, targetType string) string {
	switch targetType {
	case "boolean":
		if strings.ToLower(val) == "true" {
			return "True"
		}
		if strings.ToLower(val) == "false" {
			return "False"
		}
	case "integer":
		if _, err := strconv.ParseInt(val, 10, 64); err == nil {
			return val
		}
	case "number":
		if _, err := strconv.ParseFloat(val, 64); err == nil {
			return val
		}
	case "string":
		b, err := json.Marshal(val)
		if err == nil {
			return string(b)
		}
		return fmt.Sprintf("%q", val)
	case "array":
		entries := strings.Split(val, ",")
		quoted := make([]string, 0, len(entries))
		for _, e := range entries {
			b, _ := json.Marshal(strings.TrimSpace(e))
			quoted = append(quoted, string(b))
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	}
	if val == "true" {
		return "True"
	}
	if val == "false" {
		return "False"
	}
	if _, err := strconv.ParseInt(val, 10, 64); err == nil {
		return val
	}
	if _, err := strconv.ParseFloat(val, 64); err == nil {
		return val
	}
	b, err := json.Marshal(val)
	if err == nil {
		return string(b)
	}
	return fmt.Sprintf("%q", val)
}

type envTreeNode struct {
	name     string
	field    *envField
	children []*envTreeNode
}

func buildEnvTree(plan []envField) []*envTreeNode {
	var roots []*envTreeNode
	findOrCreate := func(list *[]*envTreeNode, name string) *envTreeNode {
		for _, n := range *list {
			if n.name == name {
				return n
			}
		}
		node := &envTreeNode{name: name}
		*list = append(*list, node)
		return node
	}

	for i := range plan {
		ef := &plan[i]
		if len(ef.path) == 0 {
			continue
		}
		curList := &roots
		for j, seg := range ef.path {
			node := findOrCreate(curList, seg)
			if j == len(ef.path)-1 {
				node.field = ef
			} else {
				curList = &node.children
			}
		}
	}
	return roots
}

// envTreeAllOptional returns true if every leaf in the subtree rooted at n is optional.
func envTreeAllOptional(n *envTreeNode) bool {
	if len(n.children) == 0 {
		return n.field != nil && n.field.optional
	}
	for _, child := range n.children {
		if !envTreeAllOptional(child) {
			return false
		}
	}
	return true
}

func kclEnvFieldGuard(e *envField) string {
	if e == nil || !e.optional {
		return ""
	}
	if e.structured.kind == rhsParam {
		if len(e.structured.paramSegs) > 0 {
			return "_spec?." + strings.Join(e.structured.paramSegs, "?.") + " != None"
		}
		if e.structured.param != "" {
			return translateParamAccessToKCL(e.structured.param) + " != None"
		}
	} else if e.structured.kind == rhsStatus {
		return kclRawStatusAccess(e.structured) + " != None"
	}
	if isNested, guardExpr := kclNestedParamGuard(e.structured, e.rhs); isNested {
		return guardExpr + " != None"
	}
	rhs := strings.TrimSpace(e.rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		inner = strings.TrimSuffix(inner, "| quote")
		inner = strings.TrimSpace(inner)
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			return translateParamAccessToKCL(param) + " != None"
		}
	}
	return ""
}

func collectKCLSubtreeGuards(n *envTreeNode, guards *[]string, seen map[string]bool) {
	if n.field != nil {
		if g := kclEnvFieldGuard(n.field); g != "" {
			if !seen[g] {
				seen[g] = true
				*guards = append(*guards, g)
			}
		}
	}
	for _, child := range n.children {
		collectKCLSubtreeGuards(child, guards, seen)
	}
}

// writeKCLEnvelopeNodes recursively renders envelope fields. If an envelope node subtree
// contains only optional leaves (no static or required fields), the entire mapping is guarded
// with `if <cond>:` so that when all child parameters evaluate to None, no empty dictionary `{}`
// is emitted in KCL (CF-291).
func writeKCLEnvelopeNodes(sb *strings.Builder, indent string, nodes []*envTreeNode, inheritedGuard string) {
	for _, n := range nodes {
		if len(n.children) > 0 {
			allOptional := envTreeAllOptional(n)
			guard := ""
			if allOptional {
				var guards []string
				seen := make(map[string]bool)
				collectKCLSubtreeGuards(n, &guards, seen)
				guard = strings.Join(guards, " or ")
			}

			wrap := guard != "" && guard != inheritedGuard
			curIndent := indent
			childInheritedGuard := inheritedGuard
			if wrap {
				sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, guard))
				curIndent = indent + "    "
				childInheritedGuard = guard
			}

			sb.WriteString(fmt.Sprintf("%s%s = {\n", curIndent, quoteKCLKey(n.name)))
			writeKCLEnvelopeNodes(sb, curIndent+"    ", n.children, childInheritedGuard)
			sb.WriteString(fmt.Sprintf("%s}\n", curIndent))
		} else if n.field != nil {
			rhs := kclStructuredRHS(n.field.structured, n.field.rhs)
			g := kclEnvFieldGuard(n.field)
			if g != "" && g != inheritedGuard {
				sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, g))
				sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.name), rhs))
			} else if n.field.structured.kind == rhsStatus {
				raw := kclRawStatusAccess(n.field.structured)
				sb.WriteString(fmt.Sprintf("%sif %s != None:\n", indent, raw))
				sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.name), rhs))
			} else if isNested, guardExpr := kclNestedParamGuard(n.field.structured, n.field.rhs); isNested {
				sb.WriteString(fmt.Sprintf("%sif %s != None:\n", indent, guardExpr))
				sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.name), rhs))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s = %s\n", indent, quoteKCLKey(n.name), rhs))
			}
		}
	}
}
