package emit

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

// kclTemplateBody generates idiomatic KCL code for function-kcl (krm.kcl.dev/v1alpha1).
func kclTemplateBody(b *blueprint.Blueprint, crds []schema.CRD) (string, error) {
	x := b.Spec.XRD
	wantNamespaced := x.Scope == "Namespaced"

	var sb strings.Builder
	sb.WriteString("# Generated by compositionfactory. Do not edit.\n")
	sb.WriteString("oxr = option(\"params\")?.oxr or {}\n")
	sb.WriteString("ocds = option(\"params\")?.ocds or {}\n")
	sb.WriteString("dxr = option(\"params\")?.dxr or {}\n")
	sb.WriteString("dcds = option(\"params\")?.dcds or {}\n")
	sb.WriteString("_spec = oxr?.spec or {}\n")
	sb.WriteString("_xr = oxr?.metadata?.name or \"\"\n")
	sb.WriteString("_xrMeta = oxr?.metadata or {}\n\n")

	sb.WriteString("_items = [\n")

	for _, r := range b.Spec.Resources {
		crd, err := resolveKind(crds, r, wantNamespaced)
		if err != nil {
			return "", err
		}

		apiVersion, err := crd.APIVersion()
		if err != nil {
			return "", fmt.Errorf("resource %q (kind %q): %w", r.Name, r.Kind, err)
		}

		if err := checkFieldPaths(r, crd); err != nil {
			return "", err
		}

		envNodes, err := checkEnvelopePaths(r, crd)
		if err != nil {
			return "", err
		}

		if err := checkStatusRefs(r, b, crds, wantNamespaced); err != nil {
			return "", err
		}

		annPlan, err := planAnnotations(r, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}

		fields := r.Fields
		if r.Provider != blueprint.NativeProvider {
			var cerr error
			fields, cerr = conventionFields(r, b, crd)
			if cerr != nil {
				return "", cerr
			}
		}
		rc := r
		rc.Fields = fields
		plan, err := planFields(rc, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}

		envPlan, err := planEnvelope(r, b, envNodes)
		if err != nil {
			return "", err
		}

		indent := "    "
		if r.When != "" {
			condKCL := translateWhenToKCL(r.When)
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, condKCL))
			indent = "        "
		}

		if r.ForEach != "" {
			loopExpr := translateForEachToKCL(r.ForEach)
			sb.WriteString(fmt.Sprintf("%sfor _i in %s:\n", indent, loopExpr))
			indent = indent + "    "
		}

		sb.WriteString(fmt.Sprintf("%s{\n", indent))
		inner := indent + "    "
		sb.WriteString(fmt.Sprintf("%sapiVersion = %q\n", inner, apiVersion))
		sb.WriteString(fmt.Sprintf("%skind = %q\n", inner, crd.Kind))

		// Metadata
		sb.WriteString(fmt.Sprintf("%smetadata = {\n", inner))
		metaInner := inner + "    "
		sb.WriteString(fmt.Sprintf("%sannotations = {\n", metaInner))
		annInner := metaInner + "    "
		if r.ForEach != "" {
			sb.WriteString(fmt.Sprintf("%s\"krm.kcl.dev/composition-resource-name\" = \"${_i}-%s\"\n", annInner, r.Name))
		} else {
			sb.WriteString(fmt.Sprintf("%s\"krm.kcl.dev/composition-resource-name\" = %q\n", annInner, r.Name))
		}
		for _, ann := range annPlan {
			rhs := kclRHS(ann.rhs)
			sb.WriteString(fmt.Sprintf("%s%q = %s\n", annInner, ann.path, rhs))
		}
		sb.WriteString(fmt.Sprintf("%s}\n", metaInner))
		sb.WriteString(fmt.Sprintf("%s}\n", inner))

		// Spec
		if crd.Native {
			sb.WriteString(fmt.Sprintf("%sspec = {\n", inner))
			writeKCLMapEntries(&sb, inner+"    ", plan)
			sb.WriteString(fmt.Sprintf("%s}\n", inner))
		} else {
			sb.WriteString(fmt.Sprintf("%sspec = {\n", inner))
			specInner := inner + "    "

			// forProvider
			sb.WriteString(fmt.Sprintf("%sforProvider = {\n", specInner))
			writeKCLMapEntries(&sb, specInner+"    ", plan)
			sb.WriteString(fmt.Sprintf("%s}\n", specInner))

			// providerConfigRef
			providerNameRef := "_spec?.providerName or \"default\""
			if p, ok := b.Spec.XRD.Parameters["providerName"]; ok && p.Default != "" {
				providerNameRef = fmt.Sprintf("_spec?.providerName or %q", p.Default)
			}
			sb.WriteString(fmt.Sprintf("%sproviderConfigRef = {\n", specInner))
			if wantNamespaced {
				sb.WriteString(fmt.Sprintf("%s    kind = \"ProviderConfig\"\n", specInner))
			}
			sb.WriteString(fmt.Sprintf("%s    name = %s\n", specInner, providerNameRef))
			sb.WriteString(fmt.Sprintf("%s}\n", specInner))

			// envelope fields
			for _, ef := range envPlan {
				rhs := kclRHS(ef.rhs)
				pathKey := strings.Join(ef.path, ".")
				sb.WriteString(fmt.Sprintf("%s%s = %s\n", specInner, quoteKCLKey(pathKey), rhs))
			}

			sb.WriteString(fmt.Sprintf("%s}\n", inner))
		}

		sb.WriteString(fmt.Sprintf("%s},\n", indent))
	}

	sb.WriteString("]\n\n")
	sb.WriteString("items = _items\n")

	return sb.String(), nil
}

func writeKCLMapEntries(sb *strings.Builder, indent string, fields []forProviderField) {
	for _, f := range fields {
		if f.isMap {
			sb.WriteString(fmt.Sprintf("%s%s = {\n", indent, quoteKCLKey(f.path)))
			writeKCLMapEntries(sb, indent+"    ", f.entries)
			sb.WriteString(fmt.Sprintf("%s}\n", indent))
			continue
		}

		rhs := kclRHS(f.rhs)
		sb.WriteString(fmt.Sprintf("%s%s = %s\n", indent, quoteKCLKey(f.path), rhs))
	}
}

func quoteKCLKey(k string) string {
	if strings.ContainsAny(k, "-./[]:") {
		return fmt.Sprintf("%q", k)
	}
	return k
}

func kclRHS(rhs string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			return translateParamAccessToKCL(param)
		}
		if strings.HasPrefix(inner, "$observed.") {
			return translateObservedAccessToKCL(inner)
		}
	}
	return kclFormatLiteral(rhs)
}

func translateParamAccessToKCL(param string) string {
	parts := strings.Split(param, ".")
	return "_spec?." + strings.Join(parts, "?.")
}

func translateObservedAccessToKCL(expr string) string {
	return expr
}

func translateWhenToKCL(when string) string {
	when = strings.TrimSpace(when)
	when = strings.ReplaceAll(when, "params.", "_spec?.")
	when = strings.ReplaceAll(when, "true", "True")
	when = strings.ReplaceAll(when, "false", "False")
	return when
}

func translateForEachToKCL(forEach string) string {
	if strings.HasPrefix(forEach, "params.") {
		param := strings.TrimPrefix(forEach, "params.")
		return fmt.Sprintf("range(0, int(_spec?.%s or 0))", param)
	}
	if strings.HasPrefix(forEach, "resources.") {
		res, path, _ := blueprint.StatusRef(forEach)
		return fmt.Sprintf("range(0, int(ocds?[%q]?.Resource?.status?.atProvider?.%s or 0))", res, strings.ReplaceAll(path, ".", "?."))
	}
	return "range(0, 0)"
}

func kclFormatLiteral(val string) string {
	if val == "true" {
		return "True"
	}
	if val == "false" {
		return "False"
	}
	if _, err := strconv.ParseInt(val, 10, 64); err == nil {
		return val
	}
	if _, err := strconv.ParseFloat(val, 64); err == nil {
		return val
	}
	b, err := json.Marshal(val)
	if err == nil {
		return string(b)
	}
	return fmt.Sprintf("%q", val)
}
