package emit

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

var (
	kclBoolTrueRE  = regexp.MustCompile(`\btrue\b`)
	kclBoolFalseRE = regexp.MustCompile(`\bfalse\b`)
)

// kclTemplateBody generates idiomatic KCL code for function-kcl (krm.kcl.dev/v1alpha1).
func kclTemplateBody(b *blueprint.Blueprint, crds []schema.CRD) (string, error) {
	if err := refuseGoTemplateOnlyFeatures(b); err != nil {
		return "", err
	}

	x := b.Spec.XRD
	wantNamespaced := x.Scope == "Namespaced"

	var sb strings.Builder
	sb.WriteString("# Generated by compositionfactory. Do not edit.\n")
	sb.WriteString("oxr = option(\"params\")?.oxr or {}\n")
	sb.WriteString("ocds = option(\"params\")?.ocds or {}\n")
	sb.WriteString("dxr = option(\"params\")?.dxr or {}\n")
	sb.WriteString("dcds = option(\"params\")?.dcds or {}\n")
	sb.WriteString("_spec = oxr?.spec or {}\n")
	sb.WriteString("_xr = oxr?.metadata?.name or \"\"\n")
	sb.WriteString("_xrMeta = oxr?.metadata or {}\n\n")

	sb.WriteString("_items = [\n")

	for _, r := range b.Spec.Resources {
		pres, err := planSingleResource(r, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}
		crd := pres.CRD
		apiVersion := pres.APIVersion
		annPlan := pres.AnnPlan
		plan := pres.Plan
		envPlan := pres.EnvPlan

		indent := "    "
		if r.When != "" {
			condKCL := translateWhenToKCL(r.When)
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, condKCL))
			indent = "        "
		}

		if r.ForEach != "" {
			sb.WriteString(fmt.Sprintf("%s*[\n", indent))
			indent = indent + "    "
		}

		sb.WriteString(fmt.Sprintf("%s{\n", indent))
		inner := indent + "    "
		sb.WriteString(fmt.Sprintf("%sapiVersion = %q\n", inner, apiVersion))
		sb.WriteString(fmt.Sprintf("%skind = %q\n", inner, crd.Kind))

		// Metadata
		sb.WriteString(fmt.Sprintf("%smetadata = {\n", inner))
		metaInner := inner + "    "
		sb.WriteString(fmt.Sprintf("%sannotations = {\n", metaInner))
		annInner := metaInner + "    "
		if r.ForEach != "" {
			sb.WriteString(fmt.Sprintf("%s\"krm.kcl.dev/composition-resource-name\" = \"%s-${_i}\"\n", annInner, r.Name))
		} else {
			sb.WriteString(fmt.Sprintf("%s\"krm.kcl.dev/composition-resource-name\" = %q\n", annInner, r.Name))
		}
		for _, ann := range annPlan {
			rhs := kclStructuredRHS(ann.structured, ann.rhs)
			if ann.structured.kind == rhsStatus {
				sb.WriteString(fmt.Sprintf("%sif %s:\n", annInner, rhs))
				sb.WriteString(fmt.Sprintf("%s    %q = %s\n", annInner, ann.path, rhs))
			} else {
				sb.WriteString(fmt.Sprintf("%s%q = %s\n", annInner, ann.path, rhs))
			}
		}
		sb.WriteString(fmt.Sprintf("%s}\n", metaInner))
		sb.WriteString(fmt.Sprintf("%s}\n", inner))

		// Spec
		if crd.Native {
			sb.WriteString(fmt.Sprintf("%sspec = {\n", inner))
			writeKCLMapEntries(&sb, inner+"    ", plan)
			sb.WriteString(fmt.Sprintf("%s}\n", inner))
		} else {
			sb.WriteString(fmt.Sprintf("%sspec = {\n", inner))
			specInner := inner + "    "

			// forProvider
			sb.WriteString(fmt.Sprintf("%sforProvider = {\n", specInner))
			writeKCLMapEntries(&sb, specInner+"    ", plan)
			sb.WriteString(fmt.Sprintf("%s}\n", specInner))

			hasPCRInPlan := false
			for _, ef := range envPlan {
				if len(ef.path) > 0 && ef.path[0] == "providerConfigRef" {
					hasPCRInPlan = true
					break
				}
			}
			if !hasPCRInPlan && wantNamespaced {
				providerNameRef := "_spec?.providerName or \"default\""
				if p, ok := b.Spec.XRD.Parameters["providerName"]; ok && p.Default != "" {
					providerNameRef = fmt.Sprintf("_spec?.providerName or %q", p.Default)
				}
				sb.WriteString(fmt.Sprintf("%sproviderConfigRef = {\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    kind = \"ClusterProviderConfig\"\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    name = %s\n", specInner, providerNameRef))
				sb.WriteString(fmt.Sprintf("%s}\n", specInner))
			}

			// envelope fields (nested objects)
			envTree := buildEnvTree(envPlan)
			writeKCLEnvelopeNodes(&sb, specInner, envTree)

			sb.WriteString(fmt.Sprintf("%s}\n", inner))
		}

		if r.ForEach != "" {
			loopExpr := translateForEachToKCL(r.ForEach)
			indent = indent[4:]
			sb.WriteString(fmt.Sprintf("%s} for _i in %s\n", indent+"    ", loopExpr))
			sb.WriteString(fmt.Sprintf("%s],\n", indent))
		} else {
			sb.WriteString(fmt.Sprintf("%s},\n", indent))
		}
	}

	sb.WriteString("]\n\n")
	sb.WriteString("items = _items\n")

	return sb.String(), nil
}

func writeKCLMapEntries(sb *strings.Builder, indent string, fields []forProviderField) {
	for _, f := range fields {
		if f.isMap {
			sb.WriteString(fmt.Sprintf("%s%s = {\n", indent, quoteKCLKey(f.path)))
			writeKCLMapEntries(sb, indent+"    ", f.entries)
			sb.WriteString(fmt.Sprintf("%s}\n", indent))
			continue
		}

		rhs := kclStructuredRHS(f.structured, f.rhs)
		if f.structured.kind == rhsStatus {
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, rhs))
			sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(f.path), rhs))
		} else {
			sb.WriteString(fmt.Sprintf("%s%s = %s\n", indent, quoteKCLKey(f.path), rhs))
		}
	}
}

func quoteKCLKey(k string) string {
	if strings.ContainsAny(k, "-./[]:") {
		return fmt.Sprintf("%q", k)
	}
	return k
}

func kclStructuredRHS(s structuredRHS, fallbackRHS string) string {
	switch s.kind {
	case rhsLiteral:
		return kclFormatLiteral(s.value, s.targetType)
	case rhsRaw:
		return s.value
	case rhsTemplate:
		return fmt.Sprintf("\"${_xr}-%s\"", s.value)
	case rhsParam:
		if len(s.paramSegs) > 0 {
			return "_spec?." + strings.Join(s.paramSegs, "?.")
		}
		return translateParamAccessToKCL(s.param)
	case rhsStatus:
		return fmt.Sprintf("ocds?[%q]?.Resource?.status?.%s", s.resource, strings.ReplaceAll(s.statusPath, ".", "?."))
	case rhsMetadata:
		return fmt.Sprintf("\"${_xr}-%s\"", s.resource)
	default:
		return kclRHS(fallbackRHS, s.targetType)
	}
}

func kclRHS(rhs string, targetType string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		inner = strings.TrimSuffix(inner, "| quote")
		inner = strings.TrimSpace(inner)
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			return translateParamAccessToKCL(param)
		}
		if strings.HasPrefix(inner, "$observed.") {
			return translateObservedAccessToKCL(inner)
		}
	}
	return kclFormatLiteral(rhs, targetType)
}

func translateParamAccessToKCL(param string) string {
	parts := strings.Split(param, ".")
	return "_spec?." + strings.Join(parts, "?.")
}

func translateObservedAccessToKCL(expr string) string {
	return expr
}

func translateWhenToKCL(when string) string {
	when = strings.TrimSpace(when)
	when = strings.ReplaceAll(when, "params.", "_spec?.")
	when = kclBoolTrueRE.ReplaceAllString(when, "True")
	when = kclBoolFalseRE.ReplaceAllString(when, "False")
	return when
}

func translateForEachToKCL(forEach string) string {
	if strings.HasPrefix(forEach, "params.") {
		param := strings.TrimPrefix(forEach, "params.")
		return fmt.Sprintf("range(0, int(_spec?.%s or 0))", param)
	}
	if strings.HasPrefix(forEach, "resources.") {
		res, path, _ := blueprint.StatusRef(forEach)
		return fmt.Sprintf("range(0, int(ocds?[%q]?.Resource?.status?.%s or 0))", res, strings.ReplaceAll(path, ".", "?."))
	}
	return "range(0, 0)"
}

func kclFormatLiteral(val string, targetType string) string {
	switch targetType {
	case "boolean":
		if strings.ToLower(val) == "true" {
			return "True"
		}
		if strings.ToLower(val) == "false" {
			return "False"
		}
	case "integer":
		if _, err := strconv.ParseInt(val, 10, 64); err == nil {
			return val
		}
	case "number":
		if _, err := strconv.ParseFloat(val, 64); err == nil {
			return val
		}
	case "string":
		b, err := json.Marshal(val)
		if err == nil {
			return string(b)
		}
		return fmt.Sprintf("%q", val)
	case "array":
		entries := strings.Split(val, ",")
		quoted := make([]string, 0, len(entries))
		for _, e := range entries {
			b, _ := json.Marshal(strings.TrimSpace(e))
			quoted = append(quoted, string(b))
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	}
	if val == "true" {
		return "True"
	}
	if val == "false" {
		return "False"
	}
	if _, err := strconv.ParseInt(val, 10, 64); err == nil {
		return val
	}
	if _, err := strconv.ParseFloat(val, 64); err == nil {
		return val
	}
	b, err := json.Marshal(val)
	if err == nil {
		return string(b)
	}
	return fmt.Sprintf("%q", val)
}

type envTreeNode struct {
	name     string
	field    *envField
	children []*envTreeNode
}

func buildEnvTree(plan []envField) []*envTreeNode {
	var roots []*envTreeNode
	findOrCreate := func(list *[]*envTreeNode, name string) *envTreeNode {
		for _, n := range *list {
			if n.name == name {
				return n
			}
		}
		node := &envTreeNode{name: name}
		*list = append(*list, node)
		return node
	}

	for i := range plan {
		ef := &plan[i]
		if len(ef.path) == 0 {
			continue
		}
		curList := &roots
		for j, seg := range ef.path {
			node := findOrCreate(curList, seg)
			if j == len(ef.path)-1 {
				node.field = ef
			} else {
				curList = &node.children
			}
		}
	}
	return roots
}

func writeKCLEnvelopeNodes(sb *strings.Builder, indent string, nodes []*envTreeNode) {
	for _, n := range nodes {
		if len(n.children) > 0 {
			sb.WriteString(fmt.Sprintf("%s%s = {\n", indent, quoteKCLKey(n.name)))
			writeKCLEnvelopeNodes(sb, indent+"    ", n.children)
			sb.WriteString(fmt.Sprintf("%s}\n", indent))
		} else if n.field != nil {
			rhs := kclStructuredRHS(n.field.structured, n.field.rhs)
			if n.field.structured.kind == rhsStatus {
				sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, rhs))
				sb.WriteString(fmt.Sprintf("%s    %s = %s\n", indent, quoteKCLKey(n.name), rhs))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s = %s\n", indent, quoteKCLKey(n.name), rhs))
			}
		}
	}
}
