package emit

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

// pythonTemplateBody generates idiomatic Python code for function-python (python.fn.crossplane.io/v1beta1 Script).
func pythonTemplateBody(b *blueprint.Blueprint, crds []schema.CRD) (string, error) {
	if err := refuseGoTemplateOnlyFeatures(b); err != nil {
		return "", err
	}

	x := b.Spec.XRD
	wantNamespaced := x.Scope == "Namespaced"

	var sb strings.Builder
	sb.WriteString("# Generated by compositionfactory. Do not edit.\n")
	sb.WriteString("from google.protobuf.json_format import MessageToDict\n")
	sb.WriteString("from crossplane.function.proto.v1 import run_function_pb2 as fnv1\n\n")
	// An optional parameter the XR omits, or a status leaf not yet observed,
	// reads as None; dropping it keeps the key out of the desired object,
	// the way the go-templating engine's hasKey guard does.
	sb.WriteString("_present = lambda d: {k: v for k, v in d.items() if v is not None}\n\n\n")
	sb.WriteString("def compose(req: fnv1.RunFunctionRequest, rsp: fnv1.RunFunctionResponse):\n")
	sb.WriteString("    oxr = MessageToDict(req.observed.composite.resource)\n")
	sb.WriteString("    ocds = {k: {\"resource\": MessageToDict(v.resource)} for k, v in req.observed.resources.items()}\n")
	sb.WriteString("    dxr = req.desired.composite.resource\n")
	sb.WriteString("    dcds = req.desired.resources\n")
	sb.WriteString("    spec = oxr.get(\"spec\", {})\n")
	sb.WriteString("    xr_name = oxr.get(\"metadata\", {}).get(\"name\", \"\")\n")
	sb.WriteString("    xr_meta = oxr.get(\"metadata\", {})\n")
	sb.WriteString("    ctx = MessageToDict(req.context)\n")
	sb.WriteString("    env = ctx.get(\"apiextensions.crossplane.io/environment\", {})\n\n")

	for _, r := range b.Spec.Resources {
		pres, err := planSingleResource(r, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}
		crd := pres.CRD
		apiVersion := pres.APIVersion
		annPlan := pres.AnnPlan
		bodyPlan := pres.BodyPlan
		envPlan := pres.EnvPlan

		indent := "    "
		if r.When != "" {
			condPython := translateWhenToPython(r.When)
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, condPython))
			indent = "        "
		}

		resKeyExpr := fmt.Sprintf("%q", r.Name)
		if r.ForEach != "" {
			loopExpr := translateForEachToPython(r.ForEach)
			sb.WriteString(fmt.Sprintf("%sfor _i in %s:\n", indent, loopExpr))
			indent = indent + "    "
			resKeyExpr = fmt.Sprintf("f\"%s-{_i}\"", r.Name)
		}

		sb.WriteString(fmt.Sprintf("%srsp.desired.resources[%s].resource.update({\n", indent, resKeyExpr))
		inner := indent + "    "
		sb.WriteString(fmt.Sprintf("%s\"apiVersion\": %q,\n", inner, apiVersion))
		sb.WriteString(fmt.Sprintf("%s\"kind\": %q,\n", inner, crd.Kind))

		// Metadata
		sb.WriteString(fmt.Sprintf("%s\"metadata\": {\n", inner))
		metaInner := inner + "    "
		if len(annPlan) > 0 {
			sb.WriteString(fmt.Sprintf("%s\"annotations\": _present({\n", metaInner))
			annInner := metaInner + "    "
			for _, ann := range annPlan {
				rhs := pythonStructuredRHS(ann.structured, ann.rhs)
				sb.WriteString(fmt.Sprintf("%s%q: %s,\n", annInner, ann.path, rhs))
			}
			sb.WriteString(fmt.Sprintf("%s}),\n", metaInner))
		}
		sb.WriteString(fmt.Sprintf("%s},\n", inner))

		// Spec
		if crd.Native {
			root, err := buildNativeTree(r.Name, bodyPlan)
			if err != nil {
				return "", err
			}
			writePythonNodes(&sb, inner, root.children)
		} else {
			sb.WriteString(fmt.Sprintf("%s\"spec\": _present({\n", inner))
			specInner := inner + "    "

			// forProvider
			sb.WriteString(fmt.Sprintf("%s\"forProvider\": _present({\n", specInner))
			root, err := buildNativeTree(r.Name, bodyPlan)
			if err != nil {
				return "", err
			}
			writePythonNodes(&sb, specInner+"    ", root.children)
			sb.WriteString(fmt.Sprintf("%s}),\n", specInner))

			hasPCRInPlan := false
			for _, ef := range envPlan {
				if len(ef.path) > 0 && ef.path[0] == "providerConfigRef" {
					hasPCRInPlan = true
					break
				}
			}
			if !hasPCRInPlan && wantNamespaced {
				providerNameRef := "spec.get(\"providerName\", \"default\")"
				if p, ok := b.Spec.XRD.Parameters["providerName"]; ok && p.Default != "" {
					providerNameRef = fmt.Sprintf("spec.get(\"providerName\", %q)", p.Default)
				}
				sb.WriteString(fmt.Sprintf("%s\"providerConfigRef\": {\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    \"kind\": \"ClusterProviderConfig\",\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    \"name\": %s,\n", specInner, providerNameRef))
				sb.WriteString(fmt.Sprintf("%s},\n", specInner))
			}

			// envelope fields (nested objects)
			envTree := buildEnvTree(envPlan)
			writePythonEnvelopeNodes(&sb, specInner, envTree)

			sb.WriteString(fmt.Sprintf("%s}),\n", inner))
		}

		sb.WriteString(fmt.Sprintf("%s})\n\n", indent))
	}

	return sb.String(), nil
}

func writePythonNodes(sb *strings.Builder, indent string, nodes []*nativeNode) {
	for i := 0; i < len(nodes); {
		c := nodes[i]
		if !c.indexed {
			writePythonNode(sb, indent, c)
			i++
			continue
		}
		j := i
		for j < len(nodes) && nodes[j].indexed && nodes[j].seg == c.seg {
			j++
		}
		run := nodes[i:j]
		i = j

		sb.WriteString(fmt.Sprintf("%s%q: [\n", indent, c.seg))
		for _, elem := range run {
			writePythonElement(sb, indent+"    ", elem)
		}
		sb.WriteString(fmt.Sprintf("%s],\n", indent))
	}
}

func writePythonNode(sb *strings.Builder, indent string, n *nativeNode) {
	if n.leaf != nil {
		rhs := pythonStructuredRHS(n.leaf.structured, n.leaf.rhs)
		sb.WriteString(fmt.Sprintf("%s%q: %s,\n", indent, n.seg, rhs))
		return
	}
	sb.WriteString(fmt.Sprintf("%s%q: _present({\n", indent, n.seg))
	writePythonNodes(sb, indent+"    ", n.children)
	sb.WriteString(fmt.Sprintf("%s}),\n", indent))
}

func writePythonElement(sb *strings.Builder, indent string, elem *nativeNode) {
	if elem.leaf != nil {
		rhs := pythonStructuredRHS(elem.leaf.structured, elem.leaf.rhs)
		sb.WriteString(fmt.Sprintf("%s%s,\n", indent, rhs))
		return
	}
	sb.WriteString(fmt.Sprintf("%s_present({\n", indent))
	writePythonNodes(sb, indent+"    ", elem.children)
	sb.WriteString(fmt.Sprintf("%s}),\n", indent))
}

func pythonStructuredRHS(s structuredRHS, fallbackRHS string) string {
	switch s.kind {
	case rhsLiteral:
		return pythonFormatLiteral(s.value, s.targetType)
	case rhsRaw:
		return s.value
	case rhsTemplate:
		return fmt.Sprintf("f\"{xr_name}-%s\"", s.value)
	case rhsParam:
		if len(s.paramSegs) > 0 {
			if len(s.paramSegs) == 1 {
				return fmt.Sprintf("spec.get(%q)", s.paramSegs[0])
			}
			var sb strings.Builder
			sb.WriteString("spec")
			for i, p := range s.paramSegs {
				if i == len(s.paramSegs)-1 {
					sb.WriteString(fmt.Sprintf(".get(%q)", p))
				} else {
					sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
				}
			}
			return sb.String()
		}
		return translateParamAccessToPython(s.param)
	case rhsStatus:
		parts := strings.Split(s.statusPath, ".")
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("ocds.get(%q, {}).get(\"resource\", {}).get(\"status\", {})", s.resource))
		for i, p := range parts {
			if p == "" {
				continue
			}
			if i == len(parts)-1 {
				sb.WriteString(fmt.Sprintf(".get(%q)", p))
			} else {
				sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
			}
		}
		return sb.String()
	case rhsMetadata:
		return fmt.Sprintf("f\"{xr_name}-%s\"", s.resource)
	case rhsEnv:
		return fmt.Sprintf("env.get(%q)", s.param)
	default:
		return pythonRHS(fallbackRHS, s.targetType)
	}
}

func pythonRHS(rhs string, targetType string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		inner = strings.TrimSuffix(inner, "| quote")
		inner = strings.TrimSpace(inner)
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			return translateParamAccessToPython(param)
		}
		if strings.HasPrefix(inner, "$env.") {
			key := strings.TrimPrefix(inner, "$env.")
			return fmt.Sprintf("env.get(%q)", key)
		}
		if strings.HasPrefix(inner, "$observed.") || strings.Contains(inner, "$observed") {
			return translateObservedAccessToPython(inner)
		}
	}
	return pythonFormatLiteral(rhs, targetType)
}

func translateParamAccessToPython(param string) string {
	parts := strings.Split(param, ".")
	if len(parts) == 1 {
		return fmt.Sprintf("spec.get(%q)", parts[0])
	}
	var sb strings.Builder
	sb.WriteString("spec")
	for i, p := range parts {
		if i == len(parts)-1 {
			sb.WriteString(fmt.Sprintf(".get(%q)", p))
		} else {
			sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
		}
	}
	return sb.String()
}

func translateObservedAccessToPython(expr string) string {
	// e.g. (index $observed.resources "role").resource.status.atProvider.arn
	if strings.Contains(expr, "index $observed.resources") {
		start := strings.Index(expr, "\"")
		end := strings.LastIndex(expr, "\"")
		if start != -1 && end != -1 && end > start {
			res := expr[start+1 : end]
			rem := expr[end+1:]
			rem = strings.TrimPrefix(rem, ").")
			rem = strings.TrimPrefix(rem, "resource.")
			parts := strings.Split(rem, ".")
			var sb strings.Builder
			sb.WriteString(fmt.Sprintf("ocds.get(%q, {}).get(\"resource\", {})", res))
			for i, p := range parts {
				if p == "" {
					continue
				}
				if i == len(parts)-1 {
					sb.WriteString(fmt.Sprintf(".get(%q, \"\")", p))
				} else {
					sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
				}
			}
			return sb.String()
		}
	}
	return expr
}

func translateWhenToPython(when string) string {
	when = strings.TrimSpace(when)
	source, name, op, literal, err := blueprint.ParseWhen(when)
	if err == nil {
		targetDict := "spec"
		if source == "env" {
			targetDict = "env"
		}
		switch op {
		case "":
			return fmt.Sprintf("bool(%s.get(%q))", targetDict, name)
		case "==":
			if literal == "true" {
				return fmt.Sprintf("bool(%s.get(%q)) is True", targetDict, name)
			}
			if literal == "false" {
				return fmt.Sprintf("bool(%s.get(%q)) is False", targetDict, name)
			}
			return fmt.Sprintf("%s.get(%q) == %s", targetDict, name, pythonFormatLiteral(literal, ""))
		case "!=":
			if literal == "true" {
				return fmt.Sprintf("bool(%s.get(%q)) is not True", targetDict, name)
			}
			if literal == "false" {
				return fmt.Sprintf("bool(%s.get(%q)) is not False", targetDict, name)
			}
			return fmt.Sprintf("%s.get(%q) != %s", targetDict, name, pythonFormatLiteral(literal, ""))
		}
	}
	for _, op := range []string{"==", "!="} {
		for _, bVal := range []string{"true", "false"} {
			suffix := fmt.Sprintf(" %s %s", op, bVal)
			if strings.HasSuffix(when, suffix) {
				prefix := strings.TrimSuffix(when, suffix)
				targetDict := "spec"
				var name string
				if strings.HasPrefix(prefix, "params.") {
					name = strings.TrimPrefix(prefix, "params.")
				} else if envKey, ok := blueprint.EnvRef(prefix); ok {
					targetDict = "env"
					name = envKey
				}
				if name != "" {
					isNot := ""
					if op == "!=" {
						isNot = " not"
					}
					pyBool := "True"
					if bVal == "false" {
						pyBool = "False"
					}
					return fmt.Sprintf("bool(%s.get(%q)) is%s %s", targetDict, name, isNot, pyBool)
				}
			}
		}
	}
	if strings.HasPrefix(when, "!params.") {
		p := strings.TrimPrefix(when, "!params.")
		return fmt.Sprintf("not bool(spec.get(%q))", p)
	}
	return when
}

func translateForEachToPython(forEach string) string {
	if strings.HasPrefix(forEach, "params.") {
		param := strings.TrimPrefix(forEach, "params.")
		return fmt.Sprintf("range(int(spec.get(%q, 0)))", param)
	}
	if key, ok := blueprint.EnvRef(forEach); ok {
		return fmt.Sprintf("range(int(env.get(%q, 0)))", key)
	}
	if strings.HasPrefix(forEach, "resources.") {
		res, path, _ := blueprint.StatusRef(forEach)
		parts := strings.Split(path, ".")
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("range(int(ocds.get(%q, {}).get(\"resource\", {}).get(\"status\", {})", res))
		for i, p := range parts {
			if i == len(parts)-1 {
				sb.WriteString(fmt.Sprintf(".get(%q, 0)))", p))
			} else {
				sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
			}
		}
		return sb.String()
	}
	return "range(0)"
}

func pythonFormatLiteral(val string, targetType string) string {
	switch targetType {
	case "boolean":
		if strings.ToLower(val) == "true" {
			return "True"
		}
		if strings.ToLower(val) == "false" {
			return "False"
		}
	case "integer":
		if i, err := strconv.ParseInt(val, 10, 64); err == nil {
			return strconv.FormatInt(i, 10)
		}
	case "number":
		if f, err := strconv.ParseFloat(val, 64); err == nil {
			return strconv.FormatFloat(f, 'f', -1, 64)
		}
	case "string":
		b, err := json.Marshal(val)
		if err == nil {
			return string(b)
		}
		return fmt.Sprintf("%q", val)
	case "array":
		entries := strings.Split(val, ",")
		quoted := make([]string, 0, len(entries))
		for _, e := range entries {
			b, _ := json.Marshal(strings.TrimSpace(e))
			quoted = append(quoted, string(b))
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	}
	if val == "true" {
		return "True"
	}
	if val == "false" {
		return "False"
	}
	if i, err := strconv.ParseInt(val, 10, 64); err == nil {
		return strconv.FormatInt(i, 10)
	}
	if f, err := strconv.ParseFloat(val, 64); err == nil {
		return strconv.FormatFloat(f, 'f', -1, 64)
	}
	b, err := json.Marshal(val)
	if err == nil {
		return string(b)
	}
	return fmt.Sprintf("%q", val)
}

func writePythonEnvelopeNodes(sb *strings.Builder, indent string, nodes []*envTreeNode) {
	for _, n := range nodes {
		if len(n.children) > 0 {
			sb.WriteString(fmt.Sprintf("%s%q: _present({\n", indent, n.name))
			writePythonEnvelopeNodes(sb, indent+"    ", n.children)
			sb.WriteString(fmt.Sprintf("%s}),\n", indent))
		} else if n.field != nil {
			rhs := pythonStructuredRHS(n.field.structured, n.field.rhs)
			sb.WriteString(fmt.Sprintf("%s%q: %s,\n", indent, n.name, rhs))
		}
	}
}
