package emit

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

// pythonTemplateBody generates idiomatic Python code for function-python (python.fn.crossplane.io/v1beta1 Script).
func pythonTemplateBody(b *blueprint.Blueprint, crds []schema.CRD) (string, error) {
	x := b.Spec.XRD
	wantNamespaced := x.Scope == "Namespaced"

	var sb strings.Builder
	sb.WriteString("# Generated by compositionfactory. Do not edit.\n")
	sb.WriteString("from crossplane.function.proto.v1 import run_function_pb2 as fnv1\n\n")
	// An optional parameter the XR omits, or a status leaf not yet observed,
	// reads as None; dropping it keeps the key out of the desired object,
	// the way the go-templating engine's hasKey guard does.
	sb.WriteString("_present = lambda d: {k: v for k, v in d.items() if v is not None}\n\n\n")
	sb.WriteString("def compose(req: fnv1.RunFunctionRequest, rsp: fnv1.RunFunctionResponse):\n")
	sb.WriteString("    oxr = req.observed.composite.resource\n")
	sb.WriteString("    ocds = req.observed.resources\n")
	sb.WriteString("    dxr = req.desired.composite.resource\n")
	sb.WriteString("    dcds = req.desired.resources\n")
	sb.WriteString("    spec = oxr.get(\"spec\", {})\n")
	sb.WriteString("    xr_name = oxr.get(\"metadata\", {}).get(\"name\", \"\")\n")
	sb.WriteString("    xr_meta = oxr.get(\"metadata\", {})\n\n")

	for _, r := range b.Spec.Resources {
		crd, err := resolveKind(crds, r, wantNamespaced)
		if err != nil {
			return "", err
		}

		apiVersion, err := crd.APIVersion()
		if err != nil {
			return "", fmt.Errorf("resource %q (kind %q): %w", r.Name, r.Kind, err)
		}

		if err := checkFieldPaths(r, crd); err != nil {
			return "", err
		}

		envNodes, err := checkEnvelopePaths(r, crd)
		if err != nil {
			return "", err
		}

		if err := checkStatusRefs(r, b, crds, wantNamespaced); err != nil {
			return "", err
		}

		annPlan, err := planAnnotations(r, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}

		fields := r.Fields
		if r.Provider != blueprint.NativeProvider {
			var cerr error
			fields, cerr = conventionFields(r, b, crd)
			if cerr != nil {
				return "", cerr
			}
		}
		rc := r
		rc.Fields = fields
		plan, err := planFields(rc, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}

		envPlan, err := planEnvelope(r, b, envNodes)
		if err != nil {
			return "", err
		}

		indent := "    "
		if r.When != "" {
			condPython := translateWhenToPython(r.When)
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, condPython))
			indent = "        "
		}

		resKeyExpr := fmt.Sprintf("%q", r.Name)
		if r.ForEach != "" {
			loopExpr := translateForEachToPython(r.ForEach)
			sb.WriteString(fmt.Sprintf("%sfor _i in %s:\n", indent, loopExpr))
			indent = indent + "    "
			resKeyExpr = fmt.Sprintf("f\"{_i}-%s\"", r.Name)
		}

		sb.WriteString(fmt.Sprintf("%srsp.desired.resources[%s].resource.update({\n", indent, resKeyExpr))
		inner := indent + "    "
		sb.WriteString(fmt.Sprintf("%s\"apiVersion\": %q,\n", inner, apiVersion))
		sb.WriteString(fmt.Sprintf("%s\"kind\": %q,\n", inner, crd.Kind))

		// Metadata
		sb.WriteString(fmt.Sprintf("%s\"metadata\": {\n", inner))
		metaInner := inner + "    "
		if len(annPlan) > 0 {
			sb.WriteString(fmt.Sprintf("%s\"annotations\": _present({\n", metaInner))
			annInner := metaInner + "    "
			for _, ann := range annPlan {
				rhs := pythonStructuredRHS(ann.structured, ann.rhs)
				sb.WriteString(fmt.Sprintf("%s%q: %s,\n", annInner, ann.path, rhs))
			}
			sb.WriteString(fmt.Sprintf("%s}),\n", metaInner))
		}
		sb.WriteString(fmt.Sprintf("%s},\n", inner))

		// Spec
		if crd.Native {
			sb.WriteString(fmt.Sprintf("%s\"spec\": _present({\n", inner))
			writePythonMapEntries(&sb, inner+"    ", plan)
			sb.WriteString(fmt.Sprintf("%s}),\n", inner))
		} else {
			sb.WriteString(fmt.Sprintf("%s\"spec\": _present({\n", inner))
			specInner := inner + "    "

			// forProvider
			sb.WriteString(fmt.Sprintf("%s\"forProvider\": _present({\n", specInner))
			writePythonMapEntries(&sb, specInner+"    ", plan)
			sb.WriteString(fmt.Sprintf("%s}),\n", specInner))

			hasPCRInPlan := false
			for _, ef := range envPlan {
				if len(ef.path) > 0 && ef.path[0] == "providerConfigRef" {
					hasPCRInPlan = true
					break
				}
			}
			if !hasPCRInPlan && wantNamespaced {
				providerNameRef := "spec.get(\"providerName\", \"default\")"
				if p, ok := b.Spec.XRD.Parameters["providerName"]; ok && p.Default != "" {
					providerNameRef = fmt.Sprintf("spec.get(\"providerName\", %q)", p.Default)
				}
				sb.WriteString(fmt.Sprintf("%s\"providerConfigRef\": {\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    \"kind\": \"ClusterProviderConfig\",\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    \"name\": %s,\n", specInner, providerNameRef))
				sb.WriteString(fmt.Sprintf("%s},\n", specInner))
			}

			// envelope fields (nested objects)
			envTree := buildEnvTree(envPlan)
			writePythonEnvelopeNodes(&sb, specInner, envTree)

			sb.WriteString(fmt.Sprintf("%s}),\n", inner))
		}

		sb.WriteString(fmt.Sprintf("%s})\n", indent))
		sb.WriteString(fmt.Sprintf("%srsp.desired.resources[%s].ready = fnv1.READY_TRUE\n\n", indent, resKeyExpr))
	}

	return sb.String(), nil
}

func writePythonMapEntries(sb *strings.Builder, indent string, fields []forProviderField) {
	for _, f := range fields {
		if f.isMap {
			sb.WriteString(fmt.Sprintf("%s%q: _present({\n", indent, f.path))
			writePythonMapEntries(sb, indent+"    ", f.entries)
			sb.WriteString(fmt.Sprintf("%s}),\n", indent))
			continue
		}

		rhs := pythonStructuredRHS(f.structured, f.rhs)
		sb.WriteString(fmt.Sprintf("%s%q: %s,\n", indent, f.path, rhs))
	}
}

func pythonStructuredRHS(s StructuredRHS, fallbackRHS string) string {
	switch s.Kind {
	case RHSLiteral:
		return pythonFormatLiteral(s.Value)
	case RHSRaw:
		return s.Value
	case RHSTemplate:
		return fmt.Sprintf("f\"{xr_name}-%s\"", s.Value)
	case RHSParam:
		if len(s.ParamSegs) > 0 {
			if len(s.ParamSegs) == 1 {
				return fmt.Sprintf("spec.get(%q)", s.ParamSegs[0])
			}
			var sb strings.Builder
			sb.WriteString("spec")
			for i, p := range s.ParamSegs {
				if i == len(s.ParamSegs)-1 {
					sb.WriteString(fmt.Sprintf(".get(%q)", p))
				} else {
					sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
				}
			}
			return sb.String()
		}
		return translateParamAccessToPython(s.Param)
	case RHSStatus:
		parts := strings.Split(s.StatusPath, ".")
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("ocds.get(%q, {}).get(\"resource\", {}).get(\"status\", {})", s.Resource))
		for i, p := range parts {
			if p == "" {
				continue
			}
			if i == len(parts)-1 {
				sb.WriteString(fmt.Sprintf(".get(%q)", p))
			} else {
				sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
			}
		}
		return sb.String()
	default:
		return pythonRHS(fallbackRHS)
	}
}

func pythonRHS(rhs string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			return translateParamAccessToPython(param)
		}
		if strings.HasPrefix(inner, "$observed.") || strings.Contains(inner, "$observed") {
			return translateObservedAccessToPython(inner)
		}
	}
	return pythonFormatLiteral(rhs)
}

func translateParamAccessToPython(param string) string {
	parts := strings.Split(param, ".")
	if len(parts) == 1 {
		return fmt.Sprintf("spec.get(%q)", parts[0])
	}
	var sb strings.Builder
	sb.WriteString("spec")
	for i, p := range parts {
		if i == len(parts)-1 {
			sb.WriteString(fmt.Sprintf(".get(%q)", p))
		} else {
			sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
		}
	}
	return sb.String()
}

func translateObservedAccessToPython(expr string) string {
	// e.g. (index $observed.resources "role").resource.status.atProvider.arn
	if strings.Contains(expr, "index $observed.resources") {
		start := strings.Index(expr, "\"")
		end := strings.LastIndex(expr, "\"")
		if start != -1 && end != -1 && end > start {
			res := expr[start+1 : end]
			rem := expr[end+1:]
			rem = strings.TrimPrefix(rem, ").")
			rem = strings.TrimPrefix(rem, "resource.")
			parts := strings.Split(rem, ".")
			var sb strings.Builder
			sb.WriteString(fmt.Sprintf("ocds.get(%q, {}).get(\"resource\", {})", res))
			for i, p := range parts {
				if p == "" {
					continue
				}
				if i == len(parts)-1 {
					sb.WriteString(fmt.Sprintf(".get(%q, \"\")", p))
				} else {
					sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
				}
			}
			return sb.String()
		}
	}
	return expr
}

func translateWhenToPython(when string) string {
	when = strings.TrimSpace(when)
	if strings.HasPrefix(when, "params.") {
		p := strings.TrimPrefix(when, "params.")
		if strings.Contains(when, "==") {
			parts := strings.SplitN(when, "==", 2)
			param := strings.TrimSpace(strings.TrimPrefix(parts[0], "params."))
			val := strings.TrimSpace(parts[1])
			if val == "true" {
				return fmt.Sprintf("bool(spec.get(%q)) is True", param)
			}
			if val == "false" {
				return fmt.Sprintf("bool(spec.get(%q)) is False", param)
			}
			return fmt.Sprintf("spec.get(%q) == %s", param, pythonFormatLiteral(val))
		}
		if strings.Contains(when, "!=") {
			parts := strings.SplitN(when, "!=", 2)
			param := strings.TrimSpace(strings.TrimPrefix(parts[0], "params."))
			val := strings.TrimSpace(parts[1])
			if val == "true" {
				return fmt.Sprintf("bool(spec.get(%q)) is not True", param)
			}
			if val == "false" {
				return fmt.Sprintf("bool(spec.get(%q)) is not False", param)
			}
			return fmt.Sprintf("spec.get(%q) != %s", param, pythonFormatLiteral(val))
		}
		return fmt.Sprintf("bool(spec.get(%q))", p)
	}
	if strings.HasPrefix(when, "!params.") {
		p := strings.TrimPrefix(when, "!params.")
		return fmt.Sprintf("not bool(spec.get(%q))", p)
	}
	return when
}

func translateForEachToPython(forEach string) string {
	if strings.HasPrefix(forEach, "params.") {
		param := strings.TrimPrefix(forEach, "params.")
		return fmt.Sprintf("range(int(spec.get(%q, 0)))", param)
	}
	if strings.HasPrefix(forEach, "resources.") {
		res, path, _ := blueprint.StatusRef(forEach)
		parts := strings.Split(path, ".")
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("range(int(ocds.get(%q, {}).get(\"resource\", {}).get(\"status\", {})", res))
		for i, p := range parts {
			if i == len(parts)-1 {
				sb.WriteString(fmt.Sprintf(".get(%q, 0)))", p))
			} else {
				sb.WriteString(fmt.Sprintf(".get(%q, {})", p))
			}
		}
		return sb.String()
	}
	return "range(0)"
}

func pythonFormatLiteral(val string) string {
	if val == "true" {
		return "True"
	}
	if val == "false" {
		return "False"
	}
	if i, err := strconv.ParseInt(val, 10, 64); err == nil {
		return strconv.FormatInt(i, 10)
	}
	if f, err := strconv.ParseFloat(val, 64); err == nil {
		return strconv.FormatFloat(f, 'f', -1, 64)
	}
	b, err := json.Marshal(val)
	if err == nil {
		return string(b)
	}
	return fmt.Sprintf("%q", val)
}

func writePythonEnvelopeNodes(sb *strings.Builder, indent string, nodes []*envTreeNode) {
	for _, n := range nodes {
		if len(n.children) > 0 {
			sb.WriteString(fmt.Sprintf("%s%q: _present({\n", indent, n.name))
			writePythonEnvelopeNodes(sb, indent+"    ", n.children)
			sb.WriteString(fmt.Sprintf("%s}),\n", indent))
		} else if n.field != nil {
			rhs := pythonStructuredRHS(n.field.structured, n.field.rhs)
			sb.WriteString(fmt.Sprintf("%s%q: %s,\n", indent, n.name, rhs))
		}
	}
}
