package emit

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

// pythonTemplateBody generates idiomatic Python code for function-python (python.fn.crossplane.io/v1beta1 Script).
func pythonTemplateBody(b *blueprint.Blueprint, crds []schema.CRD) (string, error) {
	if err := refuseGoTemplateOnlyFeatures(b); err != nil {
		return "", err
	}

	x := b.Spec.XRD
	wantNamespaced := x.Scope == "Namespaced"

	var sb strings.Builder
	sb.WriteString("# Generated by compositionfactory. Do not edit.\n")
	sb.WriteString("import base64\n")
	sb.WriteString("from google.protobuf.json_format import MessageToDict\n")
	sb.WriteString("from crossplane.function.proto.v1 import run_function_pb2 as fnv1\n\n")
	// An optional parameter the XR omits, or a status leaf not yet observed,
	// reads as None; dropping it keeps the key out of the desired object,
	// the way the go-templating engine's hasKey guard does.
	sb.WriteString("_present = lambda d: {k: v for k, v in d.items() if v is not None}\n")
	sb.WriteString("_clean_list = lambda l: [x for x in l if x is not None and (not isinstance(x, (dict, list)) or len(x) > 0)] or None\n")
	sb.WriteString("_str = lambda v: str(int(v)) if not isinstance(v, bool) and isinstance(v, (int, float)) and (isinstance(v, int) or v.is_integer()) else (str(v) if v is not None else None)\n")
	sb.WriteString("_b64 = lambda v: base64.b64encode(v if isinstance(v, bytes) else str(v).encode(\"utf-8\")).decode(\"utf-8\") if v is not None else None\n")
	sb.WriteString("_get = lambda d, *keys, default=None: default if d is None else (d if not keys else (_get(d.get(keys[0]), *keys[1:], default=default) if isinstance(d, dict) else default))\n\n\n")
	sb.WriteString("def compose(req: fnv1.RunFunctionRequest, rsp: fnv1.RunFunctionResponse):\n")
	sb.WriteString("    oxr = MessageToDict(req.observed.composite.resource)\n")
	sb.WriteString("    ocds = {k: {\"resource\": MessageToDict(v.resource)} for k, v in req.observed.resources.items()}\n")
	sb.WriteString("    dxr = req.desired.composite.resource\n")
	sb.WriteString("    dcds = req.desired.resources\n")
	sb.WriteString("    spec = oxr.get(\"spec\", {})\n")
	sb.WriteString("    xr_name = oxr.get(\"metadata\", {}).get(\"name\", \"\")\n")
	sb.WriteString("    xr_meta = oxr.get(\"metadata\", {})\n")
	sb.WriteString("    ctx = MessageToDict(req.context)\n")
	sb.WriteString("    env = ctx.get(\"apiextensions.crossplane.io/environment\", {})\n\n")

	for _, r := range b.Spec.Resources {
		pres, err := planSingleResource(r, b, crds, wantNamespaced)
		if err != nil {
			return "", err
		}
		crd := pres.CRD
		apiVersion := pres.APIVersion
		annPlan := pres.AnnPlan
		bodyPlan := pres.BodyPlan
		envPlan := pres.EnvPlan

		indent := "    "
		if r.When != "" {
			condPython := translateWhenToPython(r.When, b.Spec.Environment)
			sb.WriteString(fmt.Sprintf("%sif %s:\n", indent, condPython))
			indent = "        "
		}

		resKeyExpr := fmt.Sprintf("%q", r.Name)
		if r.ForEach != "" {
			loopExpr := translateForEachToPython(r.ForEach, b.Spec.Environment)
			sb.WriteString(fmt.Sprintf("%sfor _i in %s:\n", indent, loopExpr))
			indent = indent + "    "
			resKeyExpr = fmt.Sprintf("f\"%s-{_i}\"", r.Name)
		}

		sb.WriteString(fmt.Sprintf("%srsp.desired.resources[%s].resource.update({\n", indent, resKeyExpr))
		inner := indent + "    "
		sb.WriteString(fmt.Sprintf("%s\"apiVersion\": %q,\n", inner, apiVersion))
		sb.WriteString(fmt.Sprintf("%s\"kind\": %q,\n", inner, crd.Kind))

		// Metadata
		sb.WriteString(fmt.Sprintf("%s\"metadata\": {\n", inner))
		metaInner := inner + "    "
		if crd.Native {
			var metaName *forProviderField
			for i := range pres.MetaPlan {
				if pres.MetaPlan[i].path == "metadata.name" || pres.MetaPlan[i].path == "name" {
					metaName = &pres.MetaPlan[i]
					break
				}
			}
			if metaName != nil {
				rhs := pythonStructuredRHS(metaName.structured, metaName.rhs)
				isOptional := metaName.structured.optional || metaName.guard != "" || metaName.structured.kind == rhsStatus
				if r.ForEach != "" {
					if isOptional {
						looped := pythonLoopedRHS(rhs)
						sb.WriteString(fmt.Sprintf("%s\"name\": %s if %s else f\"{xr_name}-%s-{_i}\",\n", metaInner, looped, rhs, r.Name))
					} else {
						sb.WriteString(fmt.Sprintf("%s\"name\": %s,\n", metaInner, pythonLoopedRHS(rhs)))
					}
				} else {
					if isOptional {
						sb.WriteString(fmt.Sprintf("%s\"name\": %s or f\"{xr_name}-%s\",\n", metaInner, rhs, r.Name))
					} else {
						sb.WriteString(fmt.Sprintf("%s\"name\": %s,\n", metaInner, rhs))
					}
				}
			} else {
				if r.ForEach != "" {
					sb.WriteString(fmt.Sprintf("%s\"name\": f\"{xr_name}-%s-{_i}\",\n", metaInner, r.Name))
				} else {
					sb.WriteString(fmt.Sprintf("%s\"name\": f\"{xr_name}-%s\",\n", metaInner, r.Name))
				}
			}
		}
		if len(annPlan) > 0 {
			sb.WriteString(fmt.Sprintf("%s\"annotations\": _present({\n", metaInner))
			annInner := metaInner + "    "
			for _, ann := range annPlan {
				rhs := pythonStructuredRHS(ann.structured, ann.rhs)
				sb.WriteString(fmt.Sprintf("%s%q: %s,\n", annInner, ann.path, rhs))
			}
			sb.WriteString(fmt.Sprintf("%s}),\n", metaInner))
		}
		if crd.Native {
			otherMeta := otherNativeMetadata(pres.MetaPlan)
			if len(otherMeta) > 0 {
				root, err := buildNativeTree(r.Name, otherMeta)
				if err != nil {
					return "", err
				}
				writePythonNodes(&sb, metaInner, root.children, false)
			}
		}
		sb.WriteString(fmt.Sprintf("%s},\n", inner))

		// Spec
		if crd.Native {
			root, err := buildNativeTree(r.Name, bodyPlan)
			if err != nil {
				return "", err
			}
			writePythonNodes(&sb, inner, root.children, true)
		} else {
			sb.WriteString(fmt.Sprintf("%s\"spec\": _present({\n", inner))
			specInner := inner + "    "

			// forProvider
			sb.WriteString(fmt.Sprintf("%s\"forProvider\": _present({\n", specInner))
			root, err := buildNativeTree(r.Name, bodyPlan)
			if err != nil {
				return "", err
			}
			writePythonNodes(&sb, specInner+"    ", root.children, false)
			sb.WriteString(fmt.Sprintf("%s}),\n", specInner))

			hasPCRInPlan := false
			for _, ef := range envPlan {
				if len(ef.path) > 0 && ef.path[0] == "providerConfigRef" {
					hasPCRInPlan = true
					break
				}
			}
			if !hasPCRInPlan && wantNamespaced {
				providerNameRef := "spec.get(\"providerName\", \"default\")"
				if p, ok := b.Spec.XRD.Parameters["providerName"]; ok && p.Default != "" {
					providerNameRef = fmt.Sprintf("spec.get(\"providerName\", %q)", p.Default)
				}
				sb.WriteString(fmt.Sprintf("%s\"providerConfigRef\": {\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    \"kind\": \"ClusterProviderConfig\",\n", specInner))
				sb.WriteString(fmt.Sprintf("%s    \"name\": %s,\n", specInner, providerNameRef))
				sb.WriteString(fmt.Sprintf("%s},\n", specInner))
			}

			// envelope fields (nested objects)
			envTree := buildEnvTree(envPlan)
			writePythonEnvelopeNodes(&sb, specInner, envTree)

			sb.WriteString(fmt.Sprintf("%s}),\n", inner))
		}

		sb.WriteString(fmt.Sprintf("%s})\n\n", indent))
	}

	return sb.String(), nil
}

func writePythonNodes(sb *strings.Builder, indent string, nodes []*nativeNode, isTopLevelNative bool) {
	for i := 0; i < len(nodes); {
		c := nodes[i]
		if !c.indexed {
			writePythonNode(sb, indent, c, isTopLevelNative)
			i++
			continue
		}
		j := i
		for j < len(nodes) && nodes[j].indexed && nodes[j].seg == c.seg {
			j++
		}
		run := nodes[i:j]
		i = j

		allUncond := true
		for _, e := range run {
			u, _ := e.analyze()
			if !u {
				allUncond = false
				break
			}
		}

		if allUncond {
			sb.WriteString(fmt.Sprintf("%s%q: [\n", indent, c.seg))
		} else {
			sb.WriteString(fmt.Sprintf("%s%q: _clean_list([\n", indent, c.seg))
		}
		for _, elem := range run {
			writePythonElement(sb, indent+"    ", elem)
		}
		if allUncond {
			sb.WriteString(fmt.Sprintf("%s],\n", indent))
		} else {
			sb.WriteString(fmt.Sprintf("%s]),\n", indent))
		}
	}
}

func writePythonNode(sb *strings.Builder, indent string, n *nativeNode, isTopLevelNative bool) {
	if n.leaf != nil {
		rhs := pythonStructuredRHS(n.leaf.structured, n.leaf.rhs)
		sb.WriteString(fmt.Sprintf("%s%q: %s,\n", indent, n.seg, rhs))
		return
	}
	sb.WriteString(fmt.Sprintf("%s%q: _present({\n", indent, n.seg))
	writePythonNodes(sb, indent+"    ", n.children, false)
	if isTopLevelNative {
		sb.WriteString(fmt.Sprintf("%s}),\n", indent))
	} else {
		sb.WriteString(fmt.Sprintf("%s}) or None,\n", indent))
	}
}

func writePythonElement(sb *strings.Builder, indent string, elem *nativeNode) {
	if elem.leaf != nil {
		rhs := pythonStructuredRHS(elem.leaf.structured, elem.leaf.rhs)
		sb.WriteString(fmt.Sprintf("%s%s,\n", indent, rhs))
		return
	}
	sb.WriteString(fmt.Sprintf("%s_present({\n", indent))
	writePythonNodes(sb, indent+"    ", elem.children, false)
	sb.WriteString(fmt.Sprintf("%s}),\n", indent))
}

// pythonLoopedRHS appends the loop index _i to a metadata.name RHS expression in Python (CF-301).
func pythonLoopedRHS(rhs string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, `f"`) && strings.HasSuffix(rhs, `"`) && len(rhs) >= 3 {
		return rhs[:len(rhs)-1] + `-{_i}"`
	}
	if strings.HasPrefix(rhs, `f'`) && strings.HasSuffix(rhs, `'`) && len(rhs) >= 3 {
		return rhs[:len(rhs)-1] + `-{_i}'`
	}
	if strings.HasPrefix(rhs, `"`) && strings.HasSuffix(rhs, `"`) && len(rhs) >= 2 {
		inner := rhs[1 : len(rhs)-1]
		return fmt.Sprintf(`f"%s-{_i}"`, inner)
	}
	if strings.HasPrefix(rhs, `'`) && strings.HasSuffix(rhs, `'`) && len(rhs) >= 2 {
		inner := rhs[1 : len(rhs)-1]
		return fmt.Sprintf(`f'%s-{_i}'`, inner)
	}
	// Expression: use single quotes inside the f-string interpolation
	expr := strings.ReplaceAll(rhs, `"`, `'`)
	return fmt.Sprintf(`f"{%s}-{_i}"`, expr)
}

func pythonStructuredRHS(s structuredRHS, fallbackRHS string) string {
	switch s.kind {
	case rhsLiteral:
		return pythonFormatLiteral(s.value, s.targetType)
	case rhsRaw:
		return s.value
	case rhsTemplate:
		return fmt.Sprintf("f\"{xr_name}-%s\"", s.value)
	case rhsParam:
		var expr string
		if len(s.paramSegs) > 0 {
			if len(s.paramSegs) == 1 {
				expr = fmt.Sprintf("spec.get(%q)", s.paramSegs[0])
			} else {
				var sb strings.Builder
				sb.WriteString("_get(spec")
				for _, p := range s.paramSegs {
					sb.WriteString(fmt.Sprintf(", %q", p))
				}
				sb.WriteString(")")
				expr = sb.String()
			}
		} else {
			expr = translateParamAccessToPython(s.param)
		}
		if s.isByte {
			return fmt.Sprintf("_b64(%s)", expr)
		}
		if s.targetType == "string" && s.sourceType != "" && s.sourceType != "string" {
			return fmt.Sprintf("_str(%s)", expr)
		}
		return expr
	case rhsStatus:
		parts := strings.Split(s.statusPath, ".")
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("_get(ocds, %q, \"resource\", \"status\"", s.resource))
		for _, p := range parts {
			if p == "" {
				continue
			}
			sb.WriteString(fmt.Sprintf(", %q", p))
		}
		sb.WriteString(")")
		expr := sb.String()
		if s.isByte {
			return fmt.Sprintf("_b64(%s)", expr)
		}
		if s.targetType == "string" {
			return fmt.Sprintf("_str(%s)", expr)
		}
		return expr
	case rhsMetadata:
		expr := fmt.Sprintf("f\"{xr_name}-%s\"", s.resource)
		if s.isByte {
			return fmt.Sprintf("_b64(%s)", expr)
		}
		return expr
	case rhsEnv:
		expr := fmt.Sprintf("env.get(%q)", s.param)
		if s.hasEnvDef {
			defVal := pythonFormatLiteral(s.envDefault, s.sourceType)
			expr = fmt.Sprintf("env.get(%q, %s)", s.param, defVal)
		}
		if s.isByte {
			return fmt.Sprintf("_b64(%s)", expr)
		}
		if s.targetType == "string" && s.sourceType != "" && s.sourceType != "string" {
			return fmt.Sprintf("_str(%s)", expr)
		}
		return expr
	default:
		return pythonRHS(fallbackRHS, s.targetType)
	}
}

func pythonRHS(rhs string, targetType string) string {
	rhs = strings.TrimSpace(rhs)
	if strings.HasPrefix(rhs, "{{") && strings.HasSuffix(rhs, "}}") {
		inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(rhs, "{{"), "}}"))
		inner = strings.TrimSuffix(inner, "| quote")
		inner = strings.TrimSpace(inner)
		isByte := false
		if strings.HasSuffix(inner, "| b64enc") {
			isByte = true
			inner = strings.TrimSpace(strings.TrimSuffix(inner, "| b64enc"))
		}
		var res string
		if strings.HasPrefix(inner, "$spec.") {
			param := strings.TrimPrefix(inner, "$spec.")
			res = translateParamAccessToPython(param)
		} else if strings.HasPrefix(inner, "$env.") {
			key := strings.TrimPrefix(inner, "$env.")
			res = fmt.Sprintf("env.get(%q)", key)
		} else if strings.HasPrefix(inner, "$observed.") || strings.Contains(inner, "$observed") {
			res = translateObservedAccessToPython(inner)
		}
		if res != "" {
			if isByte {
				return fmt.Sprintf("_b64(%s)", res)
			}
			return res
		}
	}
	return pythonFormatLiteral(rhs, targetType)
}

func translateParamAccessToPython(param string) string {
	parts := strings.Split(param, ".")
	if len(parts) == 1 {
		return fmt.Sprintf("spec.get(%q)", parts[0])
	}
	var sb strings.Builder
	sb.WriteString("_get(spec")
	for _, p := range parts {
		sb.WriteString(fmt.Sprintf(", %q", p))
	}
	sb.WriteString(")")
	return sb.String()
}

func translateObservedAccessToPython(expr string) string {
	// e.g. (index $observed.resources "role").resource.status.atProvider.arn
	if strings.Contains(expr, "index $observed.resources") {
		start := strings.Index(expr, "\"")
		end := strings.LastIndex(expr, "\"")
		if start != -1 && end != -1 && end > start {
			res := expr[start+1 : end]
			rem := expr[end+1:]
			rem = strings.TrimPrefix(rem, ").")
			rem = strings.TrimPrefix(rem, "resource.")
			parts := strings.Split(rem, ".")
			var sb strings.Builder
			sb.WriteString(fmt.Sprintf("_get(ocds, %q, \"resource\"", res))
			for _, p := range parts {
				if p == "" {
					continue
				}
				sb.WriteString(fmt.Sprintf(", %q", p))
			}
			sb.WriteString(")")
			return sb.String()
		}
	}
	return expr
}

func translateWhenToPython(when string, env ...map[string]blueprint.EnvironmentKey) string {
	when = strings.TrimSpace(when)
	source, name, op, literal, err := blueprint.ParseWhen(when)
	if err == nil {
		targetDict := "spec"
		if source == "env" {
			targetDict = "env"
		}
		var envDecl blueprint.EnvironmentKey
		var hasEnvDefault bool
		if source == "env" && len(env) > 0 && env[0] != nil {
			if d, ok := env[0][name]; ok && d.Default != "" {
				envDecl = d
				hasEnvDefault = true
			}
		}

		var getExpr string
		if hasEnvDefault {
			defVal := pythonFormatLiteral(envDecl.Default, envDecl.Type)
			getExpr = fmt.Sprintf("env.get(%q, %s)", name, defVal)
		} else {
			getExpr = fmt.Sprintf("%s.get(%q)", targetDict, name)
		}

		switch op {
		case "":
			return fmt.Sprintf("bool(%s)", getExpr)
		case "==":
			return fmt.Sprintf("%s == %s", getExpr, pythonFormatLiteral(literal, "string"))
		case "!=":
			return fmt.Sprintf("%s != %s", getExpr, pythonFormatLiteral(literal, "string"))
		}
	}
	for _, op := range []string{"==", "!="} {
		for _, bVal := range []string{"true", "false"} {
			suffix := fmt.Sprintf(" %s %s", op, bVal)
			if strings.HasSuffix(when, suffix) {
				prefix := strings.TrimSuffix(when, suffix)
				targetDict := "spec"
				var name string
				var isEnv bool
				if strings.HasPrefix(prefix, "params.") {
					name = strings.TrimPrefix(prefix, "params.")
				} else if envKey, ok := blueprint.EnvRef(prefix); ok {
					targetDict = "env"
					name = envKey
					isEnv = true
				}
				if name != "" {
					isNot := ""
					if op == "!=" {
						isNot = " not"
					}
					pyBool := "True"
					if bVal == "false" {
						pyBool = "False"
					}
					var getExpr string
					if isEnv && len(env) > 0 && env[0] != nil {
						if d, ok := env[0][name]; ok && d.Default != "" {
							defVal := pythonFormatLiteral(d.Default, d.Type)
							getExpr = fmt.Sprintf("env.get(%q, %s)", name, defVal)
						}
					}
					if getExpr == "" {
						getExpr = fmt.Sprintf("%s.get(%q)", targetDict, name)
					}
					return fmt.Sprintf("bool(%s) is%s %s", getExpr, isNot, pyBool)
				}
			}
		}
	}
	if strings.HasPrefix(when, "!params.") {
		p := strings.TrimPrefix(when, "!params.")
		return fmt.Sprintf("not bool(spec.get(%q))", p)
	}
	if envKey, ok := blueprint.EnvRef(strings.TrimPrefix(when, "!")); ok && strings.HasPrefix(when, "!") {
		var getExpr string
		if len(env) > 0 && env[0] != nil {
			if d, ok := env[0][envKey]; ok && d.Default != "" {
				defVal := pythonFormatLiteral(d.Default, d.Type)
				getExpr = fmt.Sprintf("env.get(%q, %s)", envKey, defVal)
			}
		}
		if getExpr == "" {
			getExpr = fmt.Sprintf("env.get(%q)", envKey)
		}
		return fmt.Sprintf("not bool(%s)", getExpr)
	}
	return when
}

func translateForEachToPython(forEach string, env ...map[string]blueprint.EnvironmentKey) string {
	if strings.HasPrefix(forEach, "params.") {
		param := strings.TrimPrefix(forEach, "params.")
		return fmt.Sprintf("range(int(spec.get(%q, 0) or 0))", param)
	}
	if key, ok := blueprint.EnvRef(forEach); ok {
		if len(env) > 0 && env[0] != nil {
			if d, ok := env[0][key]; ok && d.Default != "" {
				defVal := pythonFormatLiteral(d.Default, d.Type)
				return fmt.Sprintf("range(int(env.get(%q, %s) or 0))", key, defVal)
			}
		}
		return fmt.Sprintf("range(int(env.get(%q, 0) or 0))", key)
	}
	if strings.HasPrefix(forEach, "resources.") {
		res, path, _ := blueprint.StatusRef(forEach)
		parts := strings.Split(path, ".")
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("range(int(_get(ocds, %q, \"resource\", \"status\"", res))
		for _, p := range parts {
			if p == "" {
				continue
			}
			sb.WriteString(fmt.Sprintf(", %q", p))
		}
		sb.WriteString(", default=0)))")
		return sb.String()
	}
	return "range(0)"
}

func pythonFormatLiteral(val string, targetType string) string {
	switch targetType {
	case "boolean":
		if strings.ToLower(val) == "true" {
			return "True"
		}
		if strings.ToLower(val) == "false" {
			return "False"
		}
	case "integer":
		if i, err := strconv.ParseInt(val, 10, 64); err == nil {
			return strconv.FormatInt(i, 10)
		}
	case "number":
		if f, err := strconv.ParseFloat(val, 64); err == nil {
			return strconv.FormatFloat(f, 'f', -1, 64)
		}
	case "string":
		b, err := json.Marshal(val)
		if err == nil {
			return string(b)
		}
		return fmt.Sprintf("%q", val)
	case "array":
		entries := strings.Split(val, ",")
		quoted := make([]string, 0, len(entries))
		for _, e := range entries {
			b, _ := json.Marshal(strings.TrimSpace(e))
			quoted = append(quoted, string(b))
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	}
	if val == "true" {
		return "True"
	}
	if val == "false" {
		return "False"
	}
	if i, err := strconv.ParseInt(val, 10, 64); err == nil {
		return strconv.FormatInt(i, 10)
	}
	if f, err := strconv.ParseFloat(val, 64); err == nil {
		return strconv.FormatFloat(f, 'f', -1, 64)
	}
	b, err := json.Marshal(val)
	if err == nil {
		return string(b)
	}
	return fmt.Sprintf("%q", val)
}

// writePythonEnvelopeNodes renders envelope fields (like writeConnectionSecretToRef).
// Optional envelope structures whose child parameters evaluate to None produce an empty
// dictionary in _present({}); "or None" converts an empty dict to None so the outer
// _present() omits the mapping entirely, avoiding Crossplane schema admission failures
// on required child properties (CF-289).
func writePythonEnvelopeNodes(sb *strings.Builder, indent string, nodes []*envTreeNode) {
	for _, n := range nodes {
		if len(n.children) > 0 {
			sb.WriteString(fmt.Sprintf("%s%q: _present({\n", indent, n.name))
			writePythonEnvelopeNodes(sb, indent+"    ", n.children)
			sb.WriteString(fmt.Sprintf("%s}) or None,\n", indent))
		} else if n.field != nil {
			rhs := pythonStructuredRHS(n.field.structured, n.field.rhs)
			sb.WriteString(fmt.Sprintf("%s%q: %s,\n", indent, n.name, rhs))
		}
	}
}
