package emit

import (
	"fmt"
	"sort"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"github.com/koorikla/compositionfactory/internal/schema"
)

// preGrantedNativeKinds is the set of native Kubernetes kinds whose RBAC
// permissions are pre-granted by Crossplane's default package manager
// cluster roles (crossplane:system:aggregate-to-crossplane).
var preGrantedNativeKinds = map[string]bool{
	"Deployment":               true,
	"Service":                  true,
	"ConfigMap":                true,
	"Secret":                   true,
	"ServiceAccount":           true,
	"CustomResourceDefinition": true,
}

// IsPreGrantedNativeKind reports whether the given kind is pre-granted by Crossplane.
func IsPreGrantedNativeKind(kind string) bool {
	return preGrantedNativeKinds[kind]
}

// rbacRule represents one policy rule in a ClusterRole.
type rbacRule struct {
	group  string
	plural string
	verbs  []string
}

// NonPreGrantedNativeRules finds all non-pre-granted native kinds composed in b
// and returns their required RBAC rules, deduplicated and sorted by (group, plural).
func NonPreGrantedNativeRules(b *blueprint.Blueprint, crds []schema.CRD) ([]rbacRule, error) {
	wantNamespaced := b.Spec.XRD.Scope == "Namespaced"
	seen := make(map[string]bool)
	var rules []rbacRule

	for _, r := range b.Spec.Resources {
		if r.Provider != blueprint.NativeProvider {
			continue
		}
		if IsPreGrantedNativeKind(r.Kind) {
			continue
		}
		crd, err := resolveKind(crds, r, wantNamespaced)
		if err != nil {
			return nil, err
		}
		key := crd.Group + "/" + crd.Plural
		if seen[key] {
			continue
		}
		seen[key] = true
		rules = append(rules, rbacRule{
			group:  crd.Group,
			plural: crd.Plural,
			verbs:  []string{"get", "list", "watch", "create", "update", "patch", "delete"},
		})
	}

	sort.Slice(rules, func(i, j int) bool {
		if rules[i].group != rules[j].group {
			return rules[i].group < rules[j].group
		}
		return rules[i].plural < rules[j].plural
	})

	return rules, nil
}

// RBAC generates a ready-to-apply ClusterRole YAML that aggregates Crossplane
// controller permissions for any non-pre-granted native Kubernetes kinds composed in b.
// If no non-pre-granted native kinds are composed, it returns nil, nil.
func RBAC(b *blueprint.Blueprint, crds []schema.CRD) ([]byte, error) {
	rules, err := NonPreGrantedNativeRules(b, crds)
	if err != nil {
		return nil, err
	}
	if len(rules) == 0 {
		return nil, nil
	}

	d := NewDoc()
	d.Line(0, "# Generated by compositionfactory. Do not edit.")
	d.Line(0, "# Source: %s", b.Metadata.Name)
	d.Line(0, "# ClusterRole granting Crossplane permissions to manage non-pre-granted native kinds.")
	d.Line(0, "apiVersion: rbac.authorization.k8s.io/v1")
	d.Line(0, "kind: ClusterRole")
	d.Line(0, "metadata:")
	roleName := fmt.Sprintf("compositionfactory:%s.%s:aggregate-to-crossplane", b.Spec.XRD.Plural, b.Spec.XRD.Group)
	if b.Spec.XRD.Group == "" {
		roleName = fmt.Sprintf("compositionfactory:%s:aggregate-to-crossplane", b.Spec.XRD.Plural)
	}
	d.Line(0, "  name: %s", roleName)
	d.Line(0, "  labels:")
	d.Line(0, `    rbac.crossplane.io/aggregate-to-crossplane: "true"`)
	d.Line(0, "rules:")
	for _, rule := range rules {
		d.Line(0, "  - apiGroups:")
		d.Line(0, "      - %q", rule.group)
		d.Line(0, "    resources:")
		d.Line(0, "      - %q", rule.plural)
		d.Line(0, "    verbs:")
		for _, verb := range rule.verbs {
			d.Line(0, "      - %s", verb)
		}
	}

	return d.Bytes(), nil
}
