package emit

import (
	"bytes"
	"strings"
	"testing"

	"github.com/koorikla/compositionfactory/internal/blueprint"
)

func testBlueprint() *blueprint.Blueprint {
	return &blueprint.Blueprint{
		APIVersion: "factory.crossplane.io/v1alpha1",
		Kind:       "Blueprint",
		Metadata:   blueprint.Metadata{Name: "xqueue"},
		Spec: blueprint.Spec{
			XRD: blueprint.XRD{
				Group: "platform.hooli.tech", Kind: "XQueue", Plural: "xqueues",
				Version: "v1alpha1", Scope: "Namespaced",
				Parameters: map[string]blueprint.Parameter{
					"location":       {Type: "string", Required: true, Enum: []string{"EU", "US"}},
					"providerName":   {Type: "string", Required: true},
					"maxMessageSize": {Type: "integer"},
				},
			},
			Resources: []blueprint.Resource{{
				Name: "main-queue", Kind: "Queue",
				Fields: map[string]blueprint.Field{
					"maxMessageSize": {From: "params.maxMessageSize"},
				},
			}},
		},
	}
}

func TestXRDShape(t *testing.T) {
	got, err := XRD(testBlueprint())
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	s := string(got)
	for _, want := range []string{
		"apiVersion: apiextensions.crossplane.io/v2",
		"kind: CompositeResourceDefinition",
		"name: xqueues.platform.hooli.tech",
		"scope: Namespaced",
		"referenceable: true",
		"enum:",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("output missing %q\n---\n%s", want, s)
		}
	}
	if strings.Contains(s, "LegacyCluster") {
		t.Error("output contains LegacyCluster, which is not valid in v2")
	}
}

// A parameter the template dereferences must be required even if the blueprint
// did not mark it so — otherwise a missing value renders "<no value>".
func TestXRDMarksDereferencedParamsRequired(t *testing.T) {
	got, _ := XRD(testBlueprint())
	s := string(got)
	if !strings.Contains(s, "required: [location, maxMessageSize, providerName]") {
		t.Errorf("required list wrong; maxMessageSize is dereferenced so it must be required\n---\n%s", s)
	}
}

func TestOutputIsDeterministicAndClean(t *testing.T) {
	a, _ := XRD(testBlueprint())
	b, _ := XRD(testBlueprint())
	if !bytes.Equal(a, b) {
		t.Error("two runs produced different bytes; output must be deterministic")
	}
	if bytes.Contains(a, []byte("\r")) {
		t.Error("output contains CR; must be LF only")
	}
	if !bytes.HasSuffix(a, []byte("\n")) || bytes.HasSuffix(a, []byte("\n\n")) {
		t.Error("output must end with exactly one newline")
	}
	for i, line := range bytes.Split(a, []byte("\n")) {
		if len(line) > 0 && (line[len(line)-1] == ' ' || line[len(line)-1] == '\t') {
			t.Errorf("line %d has trailing whitespace: %q", i+1, line)
		}
	}
}

func TestProvenanceIsACommentNotAnAnnotation(t *testing.T) {
	got, _ := XRD(testBlueprint())
	s := string(got)
	if !strings.Contains(s, "# Generated by compositionfactory") {
		t.Error("missing the do-not-edit provenance comment")
	}
	if strings.Contains(s, "annotations:") {
		t.Error("provenance must not be an annotation: it causes a perpetual ArgoCD sync loop")
	}
}
