package emit

import (
	"bytes"
	"strings"
	"testing"

	"github.com/koorikla/compositionfactory/internal/blueprint"
	"sigs.k8s.io/yaml"
)

func testBlueprint() *blueprint.Blueprint {
	return &blueprint.Blueprint{
		APIVersion: "factory.crossplane.io/v1alpha1",
		Kind:       "Blueprint",
		Metadata:   blueprint.Metadata{Name: "xqueue"},
		Spec: blueprint.Spec{
			XRD: blueprint.XRD{
				Group: "platform.sparky.ee", Kind: "XQueue", Plural: "xqueues",
				Version: "v1alpha1", Scope: "Namespaced",
				Parameters: map[string]blueprint.Parameter{
					"location":       {Type: "string", Required: true, Enum: []string{"EU", "US"}},
					"providerName":   {Type: "string", Required: true},
					"maxMessageSize": {Type: "integer"},
				},
			},
			Resources: []blueprint.Resource{{
				Name: "main-queue", Kind: "Queue",
				Fields: map[string]blueprint.Field{
					"maxMessageSize": {From: "params.maxMessageSize"},
				},
			}},
		},
	}
}

func TestXRDShape(t *testing.T) {
	got, err := XRD(testBlueprint())
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	s := string(got)
	for _, want := range []string{
		"apiVersion: apiextensions.crossplane.io/v2",
		"kind: CompositeResourceDefinition",
		"name: xqueues.platform.sparky.ee",
		"scope: Namespaced",
		"referenceable: true",
		"enum:",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("output missing %q\n---\n%s", want, s)
		}
	}
	if strings.Contains(s, "LegacyCluster") {
		t.Error("output contains LegacyCluster, which is not valid in v2")
	}
}

// required must list only the parameters the blueprint explicitly marks
// Required, not every parameter some template happens to dereference. The
// Composition emitter guards every access to a non-required parameter with
// hasKey (see composition.go), so a merely-dereferenced parameter is already
// safe from "<no value>" without also being forced into required here —
// forcing it would only strip its optionality for no safety benefit.
// maxMessageSize is dereferenced by the main-queue resource but was never
// marked Required in the blueprint, so it must be absent from this list.
func TestXRDRequiredIsExplicitOnly(t *testing.T) {
	got, err := XRD(testBlueprint())
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "required: [location, providerName]") {
		t.Errorf("required list wrong; want exactly [location, providerName] "+
			"(maxMessageSize is dereferenced but not explicitly required, so it must not appear)\n---\n%s", s)
	}
}

// A parameter that is BOTH explicitly required AND dereferenced by a template
// must still appear exactly once in required — not duplicated, and not
// dropped because it's also dereferenced.
func TestRequiredAndDereferencedAppearsOnce(t *testing.T) {
	b := testBlueprint()
	// providerName is already Required: true in testBlueprint(); also
	// dereference it from the same resource that already dereferences
	// maxMessageSize, so it is both explicitly required and dereferenced.
	b.Spec.Resources[0].Fields["providerName"] = blueprint.Field{From: "params.providerName"}

	got, err := XRD(b)
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "required: [location, providerName]") {
		t.Errorf("required list wrong; providerName is both explicitly required and "+
			"dereferenced, so it must appear exactly once, not zero or two times\n---\n%s", s)
	}
}

func TestOutputIsDeterministicAndClean(t *testing.T) {
	a, err := XRD(testBlueprint())
	if err != nil {
		t.Fatalf("XRD (first run): %v", err)
	}
	b, err := XRD(testBlueprint())
	if err != nil {
		t.Fatalf("XRD (second run): %v", err)
	}
	if !bytes.Equal(a, b) {
		t.Error("two runs produced different bytes; output must be deterministic")
	}
	if bytes.Contains(a, []byte("\r")) {
		t.Error("output contains CR; must be LF only")
	}
	if !bytes.HasSuffix(a, []byte("\n")) || bytes.HasSuffix(a, []byte("\n\n")) {
		t.Error("output must end with exactly one newline")
	}
	for i, line := range bytes.Split(a, []byte("\n")) {
		if len(line) > 0 && (line[len(line)-1] == ' ' || line[len(line)-1] == '\t') {
			t.Errorf("line %d has trailing whitespace: %q", i+1, line)
		}
	}
}

func TestProvenanceIsACommentNotAnAnnotation(t *testing.T) {
	got, _ := XRD(testBlueprint())
	s := string(got)
	if !strings.Contains(s, "# Generated by compositionfactory") {
		t.Error("missing the do-not-edit provenance comment")
	}
	if strings.Contains(s, "annotations:") {
		t.Error("provenance must not be an annotation: it causes a perpetual ArgoCD sync loop")
	}
}

// dig walks a decoded YAML/JSON document (nested map[string]any / []any, as
// produced by sigs.k8s.io/yaml) following path, failing the test immediately
// with context if any step doesn't match. A string element indexes a map; an
// int element indexes a slice.
func dig(t *testing.T, v any, path ...any) any {
	t.Helper()
	cur := v
	for i, key := range path {
		switch k := key.(type) {
		case string:
			m, ok := cur.(map[string]any)
			if !ok {
				t.Fatalf("dig %v: at step %d (%q), expected a map, got %T (%v)", path, i, k, cur, cur)
			}
			cur, ok = m[k]
			if !ok {
				t.Fatalf("dig %v: at step %d, key %q not found in %v", path, i, k, m)
			}
		case int:
			s, ok := cur.([]any)
			if !ok {
				t.Fatalf("dig %v: at step %d (index %d), expected a slice, got %T (%v)", path, i, k, cur, cur)
			}
			if k < 0 || k >= len(s) {
				t.Fatalf("dig %v: at step %d, index %d out of range (len %d)", path, i, k, len(s))
			}
			cur = s[k]
		default:
			t.Fatalf("dig %v: unsupported path element %v (%T)", path, key, key)
		}
	}
	return cur
}

// paramProps decodes the emitted XRD and returns the openAPIV3Schema
// properties map for spec.<name> parameters, i.e. the map keyed by parameter
// name whose values carry type/description/enum.
func paramProps(t *testing.T, doc []byte) map[string]any {
	t.Helper()
	var parsed map[string]any
	if err := yaml.Unmarshal(doc, &parsed); err != nil {
		t.Fatalf("emitted document is not valid YAML: %v\n---\n%s", err, doc)
	}
	props := dig(t, parsed, "spec", "versions", 0, "schema", "openAPIV3Schema",
		"properties", "spec", "properties")
	m, ok := props.(map[string]any)
	if !ok {
		t.Fatalf("parameter properties: expected a map, got %T (%v)", props, props)
	}
	return m
}

// A description containing ": " (colon-space) is a YAML mapping-value
// indicator when written as an unquoted plain scalar, so the whole document
// fails to parse. It must be quoted, and the original text must round-trip.
func TestDescriptionWithColonRoundTrips(t *testing.T) {
	want := "Region: must be EU or US"
	b := testBlueprint()
	p := b.Spec.XRD.Parameters["location"]
	p.Description = want
	b.Spec.XRD.Parameters["location"] = p

	got, err := XRD(b)
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	props := paramProps(t, got)
	desc := dig(t, props, "location", "description")
	if desc != want {
		t.Errorf("description round-tripped as %q, want %q", desc, want)
	}
}

// A description containing " #" (space then hash) starts a YAML comment when
// written as an unquoted plain scalar, so everything from the '#' onward is
// silently dropped with no parse error. It must be quoted, and the original
// text must round-trip intact, not truncated.
func TestDescriptionWithHashRoundTrips(t *testing.T) {
	want := "Region code # primary"
	b := testBlueprint()
	p := b.Spec.XRD.Parameters["location"]
	p.Description = want
	b.Spec.XRD.Parameters["location"] = p

	got, err := XRD(b)
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	props := paramProps(t, got)
	desc := dig(t, props, "location", "description")
	if desc != want {
		t.Errorf("description round-tripped as %q, want %q (must not be truncated at '#')", desc, want)
	}
}

// Enum values that look like YAML 1.1 keywords or numbers ("yes", "no",
// "1.0", "") must round-trip as the literal strings they are, not get
// reinterpreted as bool/number/null. That would silently corrupt an enum on
// a type: string field.
func TestEnumValuesRoundTripAsStrings(t *testing.T) {
	risky := []string{"yes", "no", "1.0", ""}
	b := testBlueprint()
	b.Spec.XRD.Parameters["riskyEnum"] = blueprint.Parameter{Type: "string", Enum: risky}

	got, err := XRD(b)
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	props := paramProps(t, got)
	enumAny := dig(t, props, "riskyEnum", "enum")
	enum, ok := enumAny.([]any)
	if !ok {
		t.Fatalf("enum is not a list: %T (%v)", enumAny, enumAny)
	}
	if len(enum) != len(risky) {
		t.Fatalf("enum has %d entries, want %d: %v", len(enum), len(risky), enum)
	}
	for i, want := range risky {
		got, ok := enum[i].(string)
		if !ok {
			t.Errorf("enum[%d] = %#v (%T), want string %q", i, enum[i], enum[i], want)
			continue
		}
		if got != want {
			t.Errorf("enum[%d] = %q, want %q", i, got, want)
		}
	}
}

// A string parameter's default is user-controlled free text, so it must be
// quoted the same way description is. "true" is a deliberately risky value:
// unquoted, it would be silently reinterpreted as the boolean true instead
// of the string the blueprint author wrote.
func TestStringDefaultIsQuoted(t *testing.T) {
	b := testBlueprint()
	b.Spec.XRD.Parameters["region"] = blueprint.Parameter{Type: "string", Default: "true"}

	got, err := XRD(b)
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	props := paramProps(t, got)
	def := dig(t, props, "region", "default")
	s, ok := def.(string)
	if !ok {
		t.Fatalf("default = %#v (%T), want the string %q", def, def, "true")
	}
	if s != "true" {
		t.Errorf("default = %q, want %q", s, "true")
	}
}

// An integer parameter's default must be emitted unquoted: a quoted "512"
// would be a string, a type mismatch against type: integer that gets the
// whole XRD rejected by the API server.
func TestIntegerDefaultIsUnquoted(t *testing.T) {
	b := testBlueprint()
	p := b.Spec.XRD.Parameters["maxMessageSize"]
	p.Default = "512"
	b.Spec.XRD.Parameters["maxMessageSize"] = p

	got, err := XRD(b)
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	props := paramProps(t, got)
	def := dig(t, props, "maxMessageSize", "default")
	n, ok := def.(float64)
	if !ok {
		t.Fatalf("default = %#v (%T), want the number 512", def, def)
	}
	if n != 512 {
		t.Errorf("default = %v, want 512", n)
	}
}

// A parameter with no Default set must emit no default key at all — not an
// empty string, not a null.
func TestNoDefaultEmitsNoDefaultKey(t *testing.T) {
	got, err := XRD(testBlueprint())
	if err != nil {
		t.Fatalf("XRD: %v", err)
	}
	props := paramProps(t, got)
	loc, ok := props["location"].(map[string]any)
	if !ok {
		t.Fatalf("location schema: expected a map, got %T (%v)", props["location"], props["location"])
	}
	if v, present := loc["default"]; present {
		t.Errorf("location has a default key (%#v), but Parameter.Default was never set", v)
	}
}
