// Package emit turns a blueprint into the YAML artifacts Crossplane consumes.
// Output is byte-deterministic: a churning file on a prune:true GitOps repo is
// a live-cluster incident, so determinism is a correctness requirement.
package emit

import (
	"bytes"
	"fmt"
	"strings"
)

// Doc accumulates YAML lines with guaranteed LF endings, no trailing
// whitespace, and exactly one trailing newline.
type Doc struct{ buf bytes.Buffer }

func NewDoc() *Doc { return &Doc{} }

// Line writes one line at the given indent level (two spaces per level).
func (d *Doc) Line(indent int, format string, args ...any) {
	text := fmt.Sprintf(format, args...)
	if text == "" {
		d.buf.WriteByte('\n')
		return
	}
	d.buf.WriteString(strings.Repeat("  ", indent))
	d.buf.WriteString(strings.TrimRight(text, " \t"))
	d.buf.WriteByte('\n')
}

// Comment writes a top-level comment line.
func (d *Doc) Comment(format string, args ...any) {
	// The format arg to Line must be a constant so `go vet`'s printf check
	// (which treats Line as a printf wrapper) doesn't flag this call.
	d.Line(0, "%s", "# "+fmt.Sprintf(format, args...))
}

// Bytes returns the document, normalised to exactly one trailing newline.
func (d *Doc) Bytes() []byte {
	out := bytes.ReplaceAll(d.buf.Bytes(), []byte("\r\n"), []byte("\n"))
	return append(bytes.TrimRight(out, "\n"), '\n')
}

// header is the provenance every generated file carries, as comments.
func header(d *Doc, source string) {
	d.Comment("Generated by compositionfactory. Do not edit.")
	d.Comment("Source: %s", source)
	d.Comment("Regenerate with: cf gen")
}
