// Package emit turns a blueprint into the YAML artifacts Crossplane consumes.
// Output is byte-deterministic: a churning file on a prune:true GitOps repo is
// a live-cluster incident, so determinism is a correctness requirement.
package emit

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/koorikla/compositionfactory/internal/blueprint"
)

// Doc accumulates YAML lines with guaranteed LF endings, no trailing
// whitespace, and exactly one trailing newline.
type Doc struct{ buf bytes.Buffer }

func NewDoc() *Doc { return &Doc{} }

// Line writes one line at the given indent level (two spaces per level).
func (d *Doc) Line(indent int, format string, args ...any) {
	text := fmt.Sprintf(format, args...)
	if text == "" {
		d.buf.WriteByte('\n')
		return
	}
	d.buf.WriteString(strings.Repeat("  ", indent))
	d.buf.WriteString(strings.TrimRight(text, " \t"))
	d.buf.WriteByte('\n')
}

// Comment writes a top-level comment line.
//
// format must be a compile-time string constant, not a variable: go vet's
// printf-wrapper check treats Line (and by extension Comment, since it calls
// Line) as a printf wrapper because of their (format string, args ...any)
// shape, so a call like d.Comment(someVar) fails `go build`/`go test` with a
// "non-constant format string" error that does not obviously point back here.
func (d *Doc) Comment(format string, args ...any) {
	// The format arg to Line must be a constant so `go vet`'s printf check
	// (which treats Line as a printf wrapper) doesn't flag this call.
	d.Line(0, "%s", "# "+fmt.Sprintf(format, args...))
}

// Bytes returns the document, normalised to exactly one trailing newline.
func (d *Doc) Bytes() []byte {
	out := bytes.ReplaceAll(d.buf.Bytes(), []byte("\r\n"), []byte("\n"))
	return append(bytes.TrimRight(out, "\n"), '\n')
}

// quoteYAML renders s as a YAML single-quoted scalar: '...', with any
// embedded ' doubled. Single-quoted style is valid in any YAML context (flow
// or block) and needs no escape table beyond that one doubling rule, unlike
// double-quoted style. Use this for any scalar that originates from
// user-controlled blueprint content (free text, enum values) before
// interpolating it into a document built with Line/Comment — those write raw
// text, so an unquoted value containing ": ", " #", or a value that looks
// like a YAML keyword ("yes", "1.0", "") changes the document's meaning
// instead of just its formatting.
func quoteYAML(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

var yamlKeywords = map[string]bool{
	"true": true, "false": true, "yes": true, "no": true,
	"on": true, "off": true, "null": true, "y": true, "n": true,
}

// header is the provenance every generated file carries, as comments.
func header(d *Doc, source string) {
	d.Comment("Generated by compositionfactory. Do not edit.")
	d.Comment("Source: %s", source)
	d.Comment("Regenerate with: cf gen")
}

func blueprintSource(b *blueprint.Blueprint) string {
	if b.SourcePath() != "" {
		return b.SourcePath()
	}
	return "blueprints/" + b.Metadata.Name + ".cf.yaml"
}
