/**
 * @file types.js — Core JSDoc type definitions for Composition Factory web-proto.
 *
 * Provides compile-time type validation and IDE autocomplete across API schemas,
 * blueprint IR structures, and store state containers.
 */

/**
 * FieldMapping represents a field value assignment on a composed resource.
 * Exactly one form is set: value, from, raw, or template.
 * @typedef {Object} FieldMapping
 * @property {string} [from] Reference wire (e.g. "params.myParam", "resources.myRes.status.field", "env.myKey").
 * @property {string} [value] Static literal value.
 * @property {string} [raw] Raw YAML / Go template snippet escape hatch.
 * @property {string} [template] Named template reference from spec.templates.
 */

/**
 * StatusMapping represents a cross-resource status reference or wire.
 * @typedef {Object} StatusMapping
 * @property {string} [from] Status reference expression (e.g. "resources.<name>.status.<path>").
 * @property {string} [resource] Referenced source resource name.
 * @property {string} [statusPath] Status field path on the referenced resource.
 * @property {string} [value] Optional static fallback value.
 * @property {string} [raw] Optional raw template expression.
 * @property {string} [template] Optional named template.
 */

/**
 * EnvironmentKey declares one environment variable specification in spec.environment.
 * @typedef {Object} EnvironmentKey
 * @property {string} type Data type (e.g. "string", "integer", "number", "boolean", "object").
 * @property {boolean} [required] Whether this environment key is required.
 * @property {string} [description] Human-readable documentation for this key.
 * @property {string} [default] Default value if not provided by EnvironmentConfig.
 * @property {string} [value] Value or default value of the key.
 */

/**
 * ResourceNode is one composed resource in a blueprint (doc.spec.resources[]).
 * @typedef {Object} ResourceNode
 * @property {string} name Unique resource identifier within the blueprint.
 * @property {string} kind Target Kubernetes / Crossplane kind (e.g. "Bucket", "Queue").
 * @property {string} [provider] Provider package reference or "k8s" for native kinds.
 * @property {string} [forEach] Loop count reference (e.g. "params.count").
 * @property {string} [when] Conditional render expression (e.g. "params.enabled == \"true\"").
 * @property {Record<string, FieldMapping>} [fields] Resource fields mapped by path.
 * @property {Record<string, FieldMapping>} [envelope] Crossplane spec envelope overrides.
 * @property {Record<string, FieldMapping>} [annotations] metadata.annotations entries.
 * @property {any} [connectionSecret] Connection secret configuration or references.
 */

/**
 * Parameter is one spec field of the composite XRD schema (spec.xrd.parameters).
 * @typedef {Object} Parameter
 * @property {string} type Data type ("string"|"integer"|"number"|"boolean"|"object").
 * @property {boolean} [required] Whether the parameter must be specified by the user.
 * @property {string[]} [enum] Allowed values if restricted.
 * @property {string} [default] Default value if unset.
 * @property {string} [description] User documentation for the parameter.
 * @property {Record<string, Parameter>} [properties] Nested members when type is "object".
 */

/**
 * XRD describes the composite resource definition generated by this blueprint.
 * @typedef {Object} XRD
 * @property {string} group API group (e.g. "example.org").
 * @property {string} kind Composite kind name (e.g. "XComposite").
 * @property {string} plural Plural resource name.
 * @property {string} version API version (e.g. "v1alpha1").
 * @property {string} scope "Namespaced" or "Cluster".
 * @property {Record<string, Parameter>} parameters User-configurable spec parameters.
 */

/**
 * Convention applies a template to matching fields on managed resources.
 * @typedef {Object} Convention
 * @property {string} match Suffix match pattern for field names.
 * @property {string} template Name of template in spec.templates to apply.
 */

/**
 * PipelineStep is a function step in the Composition pipeline.
 * @typedef {Object} PipelineStep
 * @property {string} name Pipeline step name.
 * @property {string} functionRef Function name reference.
 * @property {string} package OCI package reference for the function.
 * @property {string} [input] Raw YAML input configuration.
 * @property {string} [position] Relative position ("before" or "after").
 */

/**
 * BlueprintSpec defines the entire specification of a blueprint.
 * @typedef {Object} BlueprintSpec
 * @property {Array<{provider?: string, crds?: string}>} [sources] Provider OCI packages and CRD files.
 * @property {XRD} [xrd] Composite API definition.
 * @property {Record<string, EnvironmentKey>} [environment] Declared environment keys.
 * @property {Array<Object>} [environmentConfigs] Declared EnvironmentConfig references.
 * @property {Record<string, string>} [templates] Reusable Go template snippets.
 * @property {Array<Convention>} [conventions] Field conventions.
 * @property {Array<ResourceNode>} [resources] Composed resources.
 * @property {Array<PipelineStep>} [pipeline] Composition pipeline steps.
 * @property {{templateSource?: string, engine?: string}} [emit] Generator emission preferences.
 */

/**
 * Blueprint is the canonical intermediate representation document (factory.crossplane.io/v1alpha1).
 * @typedef {Object} Blueprint
 * @property {string} apiVersion "factory.crossplane.io/v1alpha1"
 * @property {string} kind "Blueprint"
 * @property {{name: string}} metadata Document metadata.
 * @property {BlueprintSpec} spec Blueprint specification.
 * @property {string} [error] Error description if operation failed.
 */

/**
 * GenerateOutput represents one rendered manifest file.
 * @typedef {Object} GenerateOutput
 * @property {string} path Destination file path relative to output directory.
 * @property {number} bytes Size of the file in bytes.
 * @property {string} body Exact YAML contents of the generated manifest.
 */

/**
 * GenerateResponse is the response body returned by POST /api/generate.
 * @typedef {Object} GenerateResponse
 * @property {Array<GenerateOutput>} outputs Rendered file outputs.
 * @property {boolean} written Whether files were written to disk.
 * @property {string} [outDir] Target output directory on the filesystem.
 * @property {string[]} [existingFiles] Pre-existing files in output directory.
 * @property {string[]} [draftWarnings] Warnings emitted during draft generation.
 */

/**
 * PreviewExpressionRequest is the request body for POST /api/preview-expression.
 * @typedef {Object} PreviewExpressionRequest
 * @property {string} expression Go template expression to evaluate.
 * @property {string} [resource] Target resource context name.
 * @property {Blueprint} [blueprint] Optional blueprint override.
 */

/**
 * PreviewExpressionResponse is the response body for POST /api/preview-expression.
 * @typedef {Object} PreviewExpressionResponse
 * @property {string} rendered Evaluated output string.
 * @property {string} [error] Evaluation error if expression failed.
 */

/**
 * RenderResponse is the response body for POST /api/render.
 * @typedef {Object} RenderResponse
 * @property {boolean} ok Whether the render succeeded.
 * @property {number} resources Number of composed resources rendered.
 * @property {string} error Error output from crossplane composition render if failed.
 * @property {string} unavailable Error description if crossplane/docker is unavailable.
 * @property {boolean} [container] Whether the backend is running in a container.
 */

/**
 * StoreState describes the client-side state in store.js.
 * @typedef {Object} StoreState
 * @property {Blueprint|null} doc The full blueprint document, exactly as last persisted.
 * @property {string|null} selectedResource Selected resource name, "xrd", or null.
 * @property {Record<string, {x: number, y: number}>} positions Canvas coordinate positions by node name.
 * @property {Set<string>} [persistedKeys] Position keys persisted in blueprint annotations.
 * @property {Array<any>} [undoStack] Undo history stack.
 * @property {Array<any>} [redoStack] Redo history stack.
 * @property {GenerateResponse|null} lastGenerate Last generation result from /api/generate.
 * @property {boolean} [generateError] Whether the last generation attempt failed.
 * @property {any} [lastAdoptReport] Loss report from adoption.
 */

/**
 * TopicMap maps each store topic to its emitted payload type.
 * @typedef {Object} TopicMap
 * @property {Blueprint} doc Emitted whenever the persisted blueprint document changes.
 * @property {string|null} selection Emitted when selectedResource changes.
 * @property {GenerateResponse} generate Emitted after a successful generate().
 * @property {{status: number, message: string, source: string}} error Emitted on failed API calls.
 */
